### ISSUE TITLE
统计之都微信二维码的图片链接失效了

### ISSUE THREAD

**Issue by XiangyunHuang** [cosname/cosx.org#1055]
链接 <https://uploads.cosx.org/images/wechat-qrcode.png> 失效了，导致主站文章末尾出现

<img width="906" alt="截屏2022-07-25 10 50 56" src="https://user-images.githubusercontent.com/12031874/180685454-16b0f18a-b2be-4fb1-b6dc-a62fe1d57b9b.png">

**Comment by yihui** [comment]
事故现场：https://github.com/cosname/uploads/commit/e3f2922adf86960124e7adc36a6409bb321e11e4 我不知道八天前 @SHL12 的一系列文件删除操作是在做什么，请编辑部核实。若是误操作，请在 git 里撤销。

**Comment by yufree** [comment]
应该是误操作，她当时应该是要给一篇待编辑文章上传图片，没注意还顺手删了一堆

**Comment by yufree** [comment]
经沟通应该是只误删了images文件夹，目前她身边没电脑，先暂时性恢复了这个文件夹内容，如果还有误删我这边来处理。

**Comment by XiangyunHuang** [comment]
应该已经修复了，我先关闭了，如果还有未修复的，可以再打开。
