### ISSUE TITLE
《统计之都》账户被禁评有一段日子了

### ISSUE THREAD

**Issue by englianhu** [cosname/cosx.org#1071]
![](https://user-images.githubusercontent.com/7227582/193462650-35cc3835-6461-4015-87f3-f4ebe4aaf563.jpg)

《统计之都》账户被禁评有一段日子了，而[简书](https://www.jianshu.com)账户前几天所有帖子都被封锁而账户似乎被禁评、今儿β站发帖也被拦截。

R文艺坊社区账户被止步半载有余，直至目前🚩中国国庆1001才解禁，回归R文艺坊社区～

请问有谁可以瞧一瞧《统计之都》账户呢？（Somebody take a look?）

- https://d.cosx.org/u/englianhu
- https://github.com/scibrokes/mytools/issues/11
- https://github.com/scibrokes/owner/issues/4

**Comment by yufree** [comment]
感谢您对统计之都的关注！恕无法回答简书与β站的问题。

至于论坛账户，在查看了您的发帖记录后请允许我用英文来精准回答您的问题，相信这也代表了部分论坛用户阅读您帖子时的感受：

> If you ask me for a straight answer, then I shall say that, as far as we can see, looking at it by and large, taking one thing with another in terms of the average of departments, then in the final analysis it is probably true to say, that at the end of the day, in general terms, you would probably find that, not to put too fine a point on it, there probably wasn't very much in it one way or the other, as far as one can see, at this stage.
