### ISSUE TITLE
统计月读（2024年8, 9月）

### ISSUE THREAD

**Issue by ZichongWang** [cosname/cosx.org#1129]
请回复 issue 进行文章推荐与招聘投稿，内容须与统计/数据科学相关，是否采纳取决于编辑部意见。

文章推荐包括学术论文、博客、书籍、教程或软件等的推荐，如果是英文文章在月报发布后自动作为翻译备选文章。

招聘主要面向学术界与工业界的招聘信息发布且岗位要与统计/数据科学相关。

文章推荐格式如下：

推荐语：（几句话就可以，可长可短，有态度不严肃）

推荐人：（建议用真名）

链接：（论文建议给doi，其余给链接）

招聘信息格式如下：

岗位介绍：（例如博士生、博后、xx公司软件工程师等）

工作地点：（具体到城市）

联系方式：（网站链接或邮箱）

**Comment by Ryanna-github** [comment]
推荐语：推荐一个小工具 `jsonlines`. python 中 json 包已经可以覆盖大部分场景，但是如果文件很大/读写多个同文件不同 json 可以尝试 `jsonlines`

推荐人：任焱

链接：https://jsonlines.readthedocs.io/en/latest/

**Comment by Ryanna-github** [comment]
推荐语：看到一个旅行地图，很有意思的呈现方式（眼前一亮）不妨点开一下感受一下新的记录方式，代码开源，自己做类似总结也可以参考一下。

推荐人：任焱

链接：https://georgios.quarto.pub/a-visual-journey-through-world-exhibitions/

**Comment by MelodyRen1998** [comment]
推荐语：在复杂的多源数据统计模型中，常见的结构假设有分组结构、低秩结构等。当存在不满足上述结构的异常个体时，如何得到模型的稳健估计？本文采用了多任务学习的方法，利用个体之间的相似性，设计出一套自适应的稳健学习方法，能够应对上述存在于复杂实际数据中的异常值问题。

推荐人：任怡萌

链接：https://projecteuclid.org/journals/annals-of-statistics/volume-51/issue-5/Adaptive-and-robust-multi-task-learning/10.1214/23-AOS2319.short

doi: 10.1214/23-AOS2319

**Comment by rucwyf** [comment]
推荐语：这篇文章简要介绍了如何使用 R 中的 {reactable} 包来创建交互式和视觉上吸引人的表格，提供了自定义列、添加摘要和美化表格的分步示例，非常适合需要提升数据展示效果的用户。

推荐人：王祎帆

链接：https://albert-rapp.de/posts/28_reactable_intro/28_reactable_intro.html

**Comment by SungManhin** [comment]
推荐语：Posit 公司最近发布 Positron release，Positron 的定位是下一代数据科学IDE，支持 R/Python，基于 VSCode 定制开发，安装后开箱即用 R 和 Python、以及 Jupyter Notebook。

推荐人：宋文轩

链接：[https://github.com/posit-dev/positron](https://github.com/posit-dev/positron), [https://www.bilibili.com/video/BV1ebhWeFEQk](https://www.bilibili.com/video/BV1ebhWeFEQk)（我翻译的一个安装和使用视频）

**Comment by SungManhin** [comment]
推荐语：在 meta 分析中，常常出现需要均值和标准差来计算总效应、而文献只给出了最大最小值、两个四分位数和中位数的情况，此时可以通过 $\lbrace a, q_1, m, q_2, b\rbrace$ 这 5 个统计量来估计均值和标准差。[Shi et al. (2020)](https://pubmed.ncbi.nlm.nih.gov/32562361/) 和 [Luo et al. (2018)](https://pubmed.ncbi.nlm.nih.gov/27683581/)的文章总结了 3 种情形下的对均值和标准差的估计并给出了在 $\lbrace a, q_1, m, q_2, b\rbrace$ 情况下的最优估计。

推荐人：宋文轩

链接：[https://pubmed.ncbi.nlm.nih.gov/32562361/](https://pubmed.ncbi.nlm.nih.gov/32562361/), [https://pubmed.ncbi.nlm.nih.gov/27683581/](https://pubmed.ncbi.nlm.nih.gov/27683581/), [https://www.math.hkbu.edu.hk/~tongt/papers/median2mean.html](https://www.math.hkbu.edu.hk/~tongt/papers/median2mean.html)

**Comment by GaakPing** [comment]
推荐语：统计学如何在大模型时代有所作为，是统计学界最关注的话题之一。Stanford的Emmanuel Candès在ASA SLDS给了一个有趣的talk，题为Statistical methods for assessing the factual accuracy of large language models, 在油管有录屏。

推荐人：陈格平

链接：https://youtu.be/fsgyllS43KY?si=3cAGiaSrvXxPdzyw

**Comment by ZichongWang** [comment]
推荐语：看到一篇总结物理和机器学习相关算法的文章，比较综述，蛮有意思的

推荐人：王子翀

链接：https://mp.weixin.qq.com/s/2mu4_c--CggMzPI_JsRF4g

**Comment by LingrenKong** [comment]
推荐语：一个有趣的算法包`surreal`，可以把你的图片（二维格点形式）加密藏进数据集，然后从线性回归的残差图中恢复出来。

推荐人：孔令仁

链接：https://r-pkg.thecoatlessprofessor.com/surreal/

**Comment by LingrenKong** [comment]
推荐语：奇怪的模因（meme）meme增加了！`memery`包提供了把R语言图表与meme图结合的功能，让你可以用meme图引人注意，为数据呈现增加趣味。

推荐人：孔令仁

链接：https://leonawicz.github.io/memery/

**Comment by ZichongWang** [comment]
推荐语：一个很不错的网站，里面有大量modern深度学习方法的代码实现，并且附带非常详细的讲解（中英文都有），包括Transformer，LoRA，Diffusion，GAN，GNN，RL等等。界面也非常漂亮，GitHub获得54k Stars，墙裂推荐

推荐人：王子翀

链接：https://nn.labml.ai/index.html, https://github.com/labmlai/annotated_deep_learning_paper_implementations

**Comment by ZichongWang** [comment]
推荐语：一篇很全的diffusion综述，里面的数学推导也非常详细，想入坑diffusion的事不错的选择

推荐人：王子翀

链接：https://arxiv.org/pdf/2208.11970

**Comment by LingrenKong** [comment]
推荐语：nala是一个基于python的apt前端，相比于apt更加容易理解和操作，而且支持并行下载包，还有自动识别Debian/Ubuntu的能力，值得一试。

推荐人：孔令仁

链接：https://github.com/volitank/nala

**Comment by LingrenKong** [comment]
月读本月收集已完成~
