### ISSUE TITLE
原站的图片、资料链接是否需要更新？

### ISSUE THREAD

**Issue by hetong007** [cosname/cosx.org#25]
目前文章里有很多形如`cos.name/wp-content/uploads/`的链接，内容是几乎所有文章的图片，以及R会演讲分享出来的资料。

在目前修改文章格式/链接的阶段，是否需要一并修改，还是未来统一脚本做替换？

**Comment by yihui** [comment]
好问题。将来用脚本统一替换吧。

**Comment by hetong007** [comment]
那将来应该有一个新的关于挪动资源的issue，这个问题留到那时候再处理吧。

**Comment by yihui** [comment]
开着吧，差不多是同一件事。

**Comment by fyears** [comment]
这个其实可以现在五分钟搞完。

1. 开一个新的 repo，把整个 `wp-content/uploads/` 文件夹 git push 到新 repo。

2. 绑定域名。比如说 `old-uploads.cosx.org`。

3. 全文替换。 `https://cos.name/wp-content/uploads/` -> `https://old-uploads.cosx.org/`。可以用 sublime 的 `ctrl+shift+f` 或者 bash 下：

    ```bash
    # linux bash or windows git-bash
    # under directory cos.org/
    find ./content -name "*.md" -exec sed -ie 's/https:\/\/cos.name\/wp-content\/uploads\//https:\/\/old-uploads.cosx.org\//g' {} \;
    ```

**Comment by fyears** [comment]
另一个相关的脚本，也写在这里算了。

现在自动导出 wp 的图片相关代码都是这样（什么鬼，为什么会这样）：

```html
[<img class="..." src="https://cos.name/wp-content/uploads/2016/08/spectrum.png" alt="spectrum" width="1024" height="448" ... />](https://cos.name/wp-content/uploads/2016/08/spectrum.png)
```

我们实际上需要的是：

```markdown
![spectrum](https://cos.name/wp-content/uploads/2016/08/spectrum.png)
```

可以使用 sed 转换 `\[<img.*alt="([^"]*)".*\/>\]\((.*)\)` -> `!\[\1\]\(\2\)`：

```bash
find ./content -name "*.md" -exec sed -i -E 's/\[<img.*alt="([^"]*)".*\/>\]\((.*)\)/!\[\1\]\(\2\)/g' {} \;
```

**Comment by yihui** [comment]
@fyears 欢迎自动化处理一下提交 PR 看看效果，谢谢！

**Comment by fyears** [comment]
@yihui 魔王说的转换图片链接需要你们把图片打包上传或者换网址，不然全变成空窗。

**Comment by yihui** [comment]
这个我们在微信上有讨论过，`https://cos.name/wp-content/uploads/` 的地址可以先不动，旧网站的 WordPress 应该会拆掉，但 `wp-content` 文件夹不会动。将来也许会移到 cosx.org 的某个子域名下，但这个任务相比起把一坨 `<img>` 代码清理成 `![]()` 来说要简单十倍。

**Comment by fyears** [comment]
应该 img 转换没啥问题。

类似的，`<a></a>` 那些转换也能用类似的方法搞定。

还有很多巨讨厌的 `<p style="text-align: center;">...</p>` 可能也可以。。。不过都很复杂。。

**Comment by yihui** [comment]
哎呀妈呀，这个事项我给忘了。这应该是从 cos.name 转 cosx.org 最重要的事项了。我们需要把 `cos.name/wp-content/` 下面的资源全都下载下来，然后传到 https://github.com/cosname/uploads 库中。回头我绑个域名 uploads.cosx.org 在这个库上，然后把旧文章中的 `cos.name/wp-content/uploads/` 替换为 `uploads.cosx.org/` 就好了。

我就是不知道过去传的那些附件加起来到底多大，搞不好会有 1G。要不 @Lchiffon 在 .md 中先自动化匹配链接下载一下看看大小？

**Comment by fyears** [comment]
为啥要自动化匹配，当然是上 vps 无脑下载啊。谢大你想把资源放在哪？

**Comment by Lchiffon** [comment]
谢大的意思是检查一遍, 然后把没引用的删除?

**Comment by yihui** [comment]
嗯，让轩哥在服务器上打个包给你也行。我确实是要去掉没用的上传资源，因为 WordPress 上传的时候老是自动生成一些不同大小的图片。

**Comment by Lchiffon** [comment]
给个权限?

**Comment by yihui** [comment]
嗻。

所以那些图片和资源加起来多大？

**Comment by Lchiffon** [comment]
我只下了相关的图片, 有一百多M
是我还漏了什么么?

**Comment by yihui** [comment]
先推上去吧（注意保持原有的`年/月/`文件夹结构），然后把链接替换为 `https://uploads.cosx.org`，然后检查一下有没有死链接（貌似你有什么 Ruby 神器之类的可以自动检查？）

**Comment by Lchiffon** [comment]
我发现了, 好像还有一些上传的文件需要迁移, 比如XXX.pdf

检查死链接不知道有啥好办法...

**Comment by fyears** [comment]
那就遍历 md 文件，把所有链接的都提取出来。
