### ISSUE TITLE
Hadley Wickham 的报导文章文字缺失

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#360]
新开一个事项，以免忘记了：https://cosx.org/2015/09/hadley-wickham-the-man-who-revolutionized-r/

事故发生地点 #232 肇事司机 @Huimincheng2015

**Comment by yihui** [comment]
来来来 @tomatoiscoding 帮个忙吧，我估计 @Huimincheng2015 最近比较忙。她的任务列表上就只剩下这半篇没有完成了。

![](https://slides.yihui.name/gif/dog-reach.gif)

**Comment by tomatoiscoding** [comment]
嗯，我来了～～～

**Comment by tomatoiscoding** [comment]
搞回来了，你瞅瞅，直接在master上提交的 @yihui

**Comment by yihui** [comment]
好，谢谢。以后如果一个 commit 的目的是关闭一项 Github 事项，可以在消息中写上要关闭的事项数字编号，比如 `Fixed #360`。这样能让每个事项底下链接到具体哪个 commit 修正了这个事项。谁的锅，谁修正的，在哪一次更新中修正的。账目一清二楚。
