### ISSUE TITLE
搜索方案

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#443]
一个可能的办法是以 Github 为中间人，在客户端浏览器中发送 GET 请求：

https://developer.github.com/v3/search/#search-code

例：

```js
$.getJSON('https://api.github.com/search/code?q=微博+in:file+language:md+repo:cosname/cosx.org')
```

得到所有 Markdown 文件路径，把这些路径转换为 cosx.org 的 URL 显示出来。

不过只能用 `$.ajax()` 而不能用 `$.getJSON()`，因为需要设置一个头字段 `Accept: application/vnd.github.v3.text-match+json` 才能返回文本结果（[如何设置](http://stackoverflow.com/a/3230824/559676)）。

没有验证的 API 请求的限制是一分钟最多10次（按 IP 计算），差不多应该也够了。

**Comment by Lchiffon** [comment]
一个小问题是这样搜索出来木有标题, 只有文件的路径诶

**Comment by yihui** [comment]
如果需要的话，标题可以用更浮夸的办法获取，直接 GET 网页再硬挖。或者每次生成一个标题与文件的映射文件，去 GET 那个文件然后把标题读回来。

**Comment by Lchiffon** [comment]
我用了后一种方法, 试试这个:
http://langdawei.com/vue-github-api/

我现在的问题是怎么把vue的东西写到hugo的theme里面, 觉得`{{}}`会冲突的样子

![image](https://cloud.githubusercontent.com/assets/7221728/25167173/fb8ba622-2510-11e7-9245-7c2d9ff1347f.png)

**Comment by yihui** [comment]
我勒个去，一不小心你又把我的工作给做完了，五体投地 🙏 我就喜欢跟这样的人合作，前一天我手指了一下，然后第二天一觉醒来发现已经做完了。

大括号我估计可能可以用这种恶心不拉几的形式实现吧：`{{"{{"}}` 和 `{{"}}"}}`

**Comment by fyears** [comment]
@Lchiffon http://stackoverflow.com/questions/33628558/vue-js-change-tags

**Comment by Lchiffon** [comment]
@fyears 我用谢大大的方法搞定了

已经推PR了 
https://github.com/cosname/hugo-steam-cos/pull/4

![image](https://cloud.githubusercontent.com/assets/7221728/25224365/c6dc0954-25f0-11e7-98cc-2daca45b90ea.png)

**Comment by fyears** [comment]
。。。你喜欢就好，不过 file.json 是不是推多了

**Comment by Lchiffon** [comment]
目前没想好啊, 后期肯定要改的, 最好还能返回简介啥的

**Comment by fyears** [comment]
@Lchiffon `file.js` 用 hugo 动态生成啊，岂不乐哉？

https://github.com/cosname/hugo-steam-cos/pull/5/files 我提交了一个参考实现。

在 `content/` 下添加一个 `archive_idx.md` 如下：

```
---
type: archive_idx
url: archive_idx.json
---
```

就可以访问 `/archive_idx.json` 页面来得到一个列表。

```json
{
  "posts": [
  
    {
      "title": "第十届中国R会议（北京）会议通知",
      "link": "//localhost:1313/2017/04/chinar-2017-bj-announcement/",
      "date": "2017-04-05"
    },
  
    {
      "title": "ggimage：ggplot2中愉快地使用图片",
      "link": "//localhost:1313/2017/03/ggimage/",
      "date": "2017-03-29"
    },
  
    {
      "title": "Posts",
      "link": "//localhost:1313/post/",
      "date": "2017-04-05"
    },
  
  ],
}
```

**Comment by yihui** [comment]
小黄这个解决方案满分。Hugo 居然会保留扩展名 .json？好神奇。

**Comment by Lchiffon** [comment]
厉害了!

**Comment by fyears** [comment]
还想过更邪的招：直接把所有文章的内容塞进 json 里面，搜索此 json 即可。

可是生成出来的 json 有 6 mb 大小，不是很合适。

那么问题来了，国外用户 github 很快，下载 6 mb json 也很快；国内用户 github 很慢，下载 6 mb json 也很慢。任君选择~🙄

**Comment by Lchiffon** [comment]
这样不好吧, 万一一个手机用户点了cos.name....

**Comment by fyears** [comment]
鉴于 https://github.com/cosname/hugo-steam-cos/pull/4 遇到了问题。。。

我 propose 另一个简单粗暴的方案：使用 google 或者 bing。。。。

由于众所周知的原因，用 bing 是更加靠谱的，比如说这个，每次都加上 `site: cos.name` 在末尾就好了：

https://www.bing.com/search?q=r+site%3Acos.name

**Comment by yihui** [comment]
这个方案唯一的问题是要仰仗搜索引擎的收录速度，但说实话我也不知道 bing 和 Github 谁收录速度更快，反正应该是都有延迟。

**Comment by yihui** [comment]
这是另一种选择：https://www.algolia.com/pricing 免费方案只支持一万条记录和每个月十万次搜索，我估计对我们可能也够了，如果超过十万次，我们可以重定向到 Bing 上。

**Comment by fyears** [comment]
algolia 是不错，就是有些折腾。我看了看，需要手动写一个 hugo 插件更新它的数据库，除此之外都挺好的。

（不如我们自己搞一个类似的，用后台 grep 驱动的搜索服务算了！（逃

**Comment by Lchiffon** [comment]
[这里](https://blog.noty.im/posts/setup-full-text-search-with-hugo/)有一篇用gulp打包hugo的post成algolia的index内容, 但过程中应该是用node做的, 这个过程在travis-ci应该可以实现?

**Comment by yihui** [comment]
肯定可以啊，不过这个可能有一点不靠谱，我粗略看了一下，它可能是认为 content/foo.md 一定会生成 /foo/ 链接，这个假设不合理，比如 content/post/xxx-xx-xx-foo.md 可能会生成 /xxxx/xx/foo/ 这个要根据 config.toml 中的 permalinks 来决定。你可以重新写一个脚本来生成这个 JSON。

**Comment by Lchiffon** [comment]
用gulp写了一个打包index.json的方式, 全自动上传algolia. 涉及到一些token就没push出来.

搜索的服务 抄抄代码做出来了一套, 可以先看下

http://langdawei.com/vue-github-api/algolia/?q=%E8%B0%A2%E7%9B%8A%E8%BE%89&hPP=10&idx=cosx.org&p=0&is_v=1

下来一个问题是travis.yml在哪里编辑?可以用我的账号监控这个repo的变化么?

**Comment by yihui** [comment]
我不太想对这个库启用 Travis，因为跑 Travis 太慢了，不利于 PR 快速编译预览。我想的是另外建一个库，在那个库中用 cron https://docs.travis-ci.com/user/cron-jobs/ 每天编译索引传 Algolia（如果没有变化就不用传了）。你可以自己建一个 cosx-search 库试试。

**Comment by Lchiffon** [comment]
好的, 我试一下
不过每次传Algolia也会耗流量的, 一个月30次, 就是1W多的流量, 差不多十分之一就没了

我想我最好能判断下这天有没有更新文章

**Comment by fyears** [comment]
@Lchiffon 强啊！

1. algolia token 之类的写在 travis 里的 Environment Variables 里，repo 的 travis.yml 应该是不包含任何敏感信息的。
2. 我没和人用过，不过我猜测 travis 对同一个 repo 的设置，只要有管理员权限就会共享一份？那么就挺方便的。（cosname 的 repo 我都没权限，没试验过，逃
3. algolia 要不要注册一个公共账号啥的？@yihui @yixuan 用私人账号不太方便吧。
4. 判断更新记录可以用 [api](https://developer.github.com/v3/repos/commits/)，比如说 `https://api.github.com/repos/cosname/cosx.org/commits?since=2017-05-16T00:00:00Z` （注意 `T` 和 `Z` ），只要不为空，就是有 commit 的，不能再爽。

**Comment by fyears** [comment]
在原文的 `index` task 里，用一个 fetch 获取 commits 然后把任务塞在判断 commits 数目里

```js
let commits_url = 'https://api.github.com/repos/cosname/cosx.org/commits?since=2017-05-16T00:00:00Z';
fetch(commits_url )
  .then(resp=>resp.json())
  .then(commits=>{
    if (commits.length > 0) {
      ...
    }
  })
```

**Comment by tomatoiscoding** [comment]
小黄的如此这般好萌好萌啊 😂  @fyears

**Comment by Lchiffon** [comment]
@fyears 完美

已经搞好这部分了, 可以做搜索页面了...

自动代码在这里: https://github.com/Lchiffon/cosx-algolia
我想, 如果一个账号流量不够, 我们可以多申请几个免费账号?
逃)

**Comment by Lchiffon** [comment]
我发现小黄你的代码都是 let+fetch的风格哈哈哈

**Comment by yihui** [comment]
如果流量不够了就往 Bing 那边转吧。我不知道 Bing 有没有类似 Google Webmaster 的服务可以提交 sitemap.xml。

**Comment by Lchiffon** [comment]
好像有 https://www.bing.com/toolbox/webmaster :cry:

**Comment by yihui** [comment]
要是 Bing 那边能提交 sitemap.xml 的话，就把这个提交了吧：https://cosx.org/sitemap.xml 我刚提交给谷歌了。这个不是特别重要。

好了，这个事项应该算是完工了。谢谢各位！

**Comment by Lchiffon** [comment]
我怎么没看到sitemap.xml是写在哪里生成的, 有个bing的xml也要上传...

**Comment by yihui** [comment]
sitemap.xml 是 Hugo 自动生成的。

Bing 要求上传的文件你放到 https://github.com/cosname/cosx.org/tree/master/static 目录下就好了。

**Comment by Lchiffon** [comment]
好了, 完成~
