### ISSUE TITLE
Processing.R 文章

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#542]
@gaocegege 等你的 GOSC 项目完成后，欢迎给统计之都投稿介绍一下这个项目和成果。谢谢！

https://github.com/gaocegege/Processing.R

**Comment by gaocegege** [comment]
My pleasure :)

**Comment by gaocegege** [comment]
你好，我似乎是 Bug 体质，在论坛发帖的过程中遇到了一个问题：

我发的帖子不会出现在首页的 Timeline 中，但是根据 URL 访问又是可以的。与此同时编辑内容会返回 500，请问可以帮忙删帖一下我重新来么 Orz

ref http://cos.name/cn/topic/418615/

**Comment by yihui** [comment]
你等过两周了我们完成改版了再到新论坛发吧，我也不知道这个论坛现在出什么问题了，今天我自己访问也不太顺畅，经常 500

抄送 @yixuan

**Comment by gaocegege** [comment]
好的，谢谢

**Comment by yihui** [comment]
@gaocegege 考虑一下参与评奖：http://asa.stat.uconn.edu 不过你最好是再多花一点功夫在统计方面，现在它几乎是一件纯计算机、艺术作品。要是能有一些统计方面的例子，会大大增加它中奖的概率。你还有大约两个月时间。

**Comment by gaocegege** [comment]
谢谢，我去看看 :)

**Comment by yihui** [comment]
FlowingData 等着英雄去揭榜：http://flowingdata.com/2017/12/04/drawing-with-noise/
