### ISSUE TITLE
COS访谈第二十七期：出国申请经验分享

### ISSUE THREAD

**Issue by Lchiffon** [cosname/cosx.org#545]
需要迁移至主站

请等我投稿指南写完 :(
#58

**Comment by Lchiffon** [comment]
以及写完了, 以及29期也没放...

**Comment by yihui** [comment]
最近微信里究竟有几篇跟这边不同步？以后要确保流程是先编辑这边的文章，完了之后再编微信。

现在除了投稿指南，基本上已经可以把旧站转向新站了。感觉拖得越久，越容易出现微信跟主站不同步的情况。

**Comment by Lchiffon** [comment]
应该是三篇, 27期, 29期访谈, 以及合肥的会议通知

**Comment by yihui** [comment]
这个可以关了吧。不过我还是那个问题，谁去看看有没有漏掉的微信文章这边没有发布的。

**Comment by Lchiffon** [comment]
我先关了, 有文章的我再开issue
