### ISSUE TITLE
黄湘云的随机数文章

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#549]
参见编辑部邮箱。

**Comment by tomatoiscoding** [comment]
我看了一下，她里面的代码块都是运行起来的。。。是要作者改改还是我们自己来改？ @yihui

**Comment by yihui** [comment]
请作者自己操刀吧。他热情挺高的。你可以回邮件问问他有没有 Github 账号，要是知道怎么发 PR 的话，我们可以请他直接发 PR，那样最方便。

**Comment by Cloud2016** [comment]
github账户我有，PR没操作过

**Comment by Cloud2016** [comment]
Github 账户我有，PR没操作过

**Comment by Cloud2016** [comment]
我把源代码和文档传至 Github 上了[https://github.com/Cloud2016/RNG](url)

**Comment by Cloud2016** [comment]
我把wiki看了下，理解是我来写md文件，感觉本地做肯定是没问题（这个可以照之前的post目录下的md文档来），然后上传到cosx的github不会搞，要不我在本地做好md之后，把里面包含的图片一并发给cos编辑部吧

**Comment by Cloud2016** [comment]
我把wiki看了下，理解是我来写md文件，感觉本地做肯定是没问题（这个可以照之前的post目录下的md文档来），然后上传到cosname/cosx.org的github不会搞，要不我在本地做好md之后，把里面包含的图片一并发给cos编辑部吧

**Comment by Lchiffon** [comment]
PR没怎么搞过可以看下这个:
https://deploy-preview-552--cosx.netlify.com/2017/05/work-with-cos/#web
然后你可以把图发给我们或者直接上传

比如直接把图片拖在github评论框里面就会生成图片的markdown代码

**Comment by Lchiffon** [comment]
如果你觉得麻烦就编译一个md发给我们吧~

**Comment by Cloud2016** [comment]
PR好像还是没有学会，先本地编辑好，再发给编辑部吧

**Comment by Cloud2016** [comment]
我已经编辑好了，放在我的[github](https://github.com/Cloud2016/random-number/tree/master/cos%20random%20number)下，请编辑部审阅 @Lchiffon

**Comment by Lchiffon** [comment]
已经做了PR: #557 
预览见:
https://deploy-preview-557--cosx.netlify.com/2017/05/random-number-generation-and-its-application-to-statistical-simulation/

**Comment by Cloud2016** [comment]
辛苦了，谢谢
