### ISSUE TITLE
从Rmd文件发布post

### ISSUE THREAD

**Issue by chengjunhou** [cosname/cosx.org#551]
附带的问题有如何处理图片。

向谢大，大为咨询后解决方案如下：
1. 在Rmd文件起始部分添加如下设定，render成HTML同时，也会保留md文件。直接发布md文件即可。
```
output: 
  html_document: 
    keep_md: true
```
2. 图片目前上传到个人github repository下专门开的issue里。

可以考虑把这几条加入编辑手册。

**Comment by yihui** [comment]
非也，我不是要建议 `keep_md: true`。如果是 Rmd 文章，只有一条路走，就是 `blogdown::serve_site()`。对作者来说，把看到的所有新生成的文件都推送进 PR 就好了，剩下的事就是该编辑操心的事了。

负责合并的编辑需要看预览页面，把 foo.Rmd 生成的 foo.html 文件中的图片地址修改为预览页面上的图片地址，删掉 PR 中的图片文件，然后合并。这样图片文件本身不会进入主库，主库中只留下预览页面上的图片链接，从读者的角度来说看不出区别，从我们的角度来说会大幅节省主库的空间。不知道编辑部的 CTO @Lchiffon 以及副主编 @tomatoiscoding 听懂我这无比抠门的主意了没有。

**Comment by tomatoiscoding** [comment]
got it

**Comment by yihui** [comment]
当然，把图片重新上传 Github 也行，就是更麻烦一点。还是薅 Netlify 的羊毛吧。这个事情应该可以有自动化的可能性，就是说起来太费脑子了，我最近有点内存不足。

**Comment by tomatoiscoding** [comment]
资源能薅就薅，代码能抄就抄 @yihui

**Comment by yihui** [comment]
假装击个掌 ✋
