### ISSUE TITLE
重定向投稿指南

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#561]
重定向

- http://cos.name/2008/11/how-to-work-with-cos/
- http://cos.name/2008/11/how-to-work-with-cos-2/

到 #552

**Comment by Lchiffon** [comment]
已发布 <https://cosx.org/2017/05/work-with-cos/>

**Comment by yihui** [comment]
我又看了一遍，内容还需要再修改。维基中的东西不能照搬过来，那里面说的是搬家的注意事项，有些不适用于新投稿。我在 #584 中略改了一下。

在修改完之前，这个事项暂时不要关闭。

**Comment by yihui** [comment]
修改完毕。关门。
