### ISSUE TITLE
添加文章评论链接

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#562]
因为多说垮掉了，Disqus 墙掉了，我们计划把主站文章评论引入到论坛。轩哥已经做好了数据库和论坛准备工作，现在主站方面就差一个地方插入评论链接（可以是个大按钮），链到论坛帖子上。在具体实现上，我想就用一个 YAML 变量吧，比如 `comment_id: 12345`，Hugo 模板里用 `{{ with .Params.comment_id }}https://d.cosx.org/d/{{ . }}{{ end }}` 写出链接。

**Comment by yixuan** [comment]
在 https://github.com/cosname/cosx.org/commit/b910ad0670944195441eecd1e73cc4e2c7f1e6df 中已实现。
