### ISSUE TITLE
R会议标签下文章更新

### ISSUE THREAD

**Issue by XueningZhu** [cosname/cosx.org#566]
更新第六届R会议之后的文章到“R会议标签下” @xiaoningwang

**Comment by yihui** [comment]
这个任务请先等一等。我觉得现在的页面设置不太科学，需要再想一想。

**Comment by yufree** [comment]
目前打算把主页底部R会议直接链接到 <https://china-r.org/> ，这样就不再单独在主站维护会议页面而是统一转给 <https://github.com/cosname/R-conference> 来维护，主站依然会发布会议信息，可通过文章分类来索引。
