### ISSUE TITLE
二维码图片

### ISSUE THREAD

**Issue by Lchiffon** [cosname/cosx.org#567]
二维码图片死了, 默哀~

https://cos.name/wp-content/uploads/2017/02/qrcode_for_gh_946beec24de4_1280-300x300.jpg

**Comment by yihui** [comment]
请帮忙移到 uploads 库中（改成一个正常人类用的文件名）：

![image](https://user-images.githubusercontent.com/163582/28002018-d54e6398-64f6-11e7-9d99-ce017c86e4e0.png)

**Comment by yihui** [comment]
#568 已经修正。
