### ISSUE TITLE
最新几篇文章的论坛帖子

### ISSUE THREAD

**Issue by yixuan** [cosname/cosx.org#575]
1. 给编辑部设置好论坛 COSeditor 的账号
2. 给最新的几篇主站文章加上论坛链接
3. 在编辑部的维基中说明以后发表文章的流程

**Comment by yihui** [comment]
所以这个问题现在算是解决完了吗？

**Comment by yixuan** [comment]
对， @Perfectizer 已经完成了。

**Comment by yihui** [comment]
林主席花名略多，每次看见一个名字要愣一下才能反应过来是谁。心里默念三遍：苏云书、Perfectizer 是林枫的马甲，马甲，马甲。
