### ISSUE TITLE
延迟加载论坛 iframe

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#577]
延迟加载，节省带宽和服务器资源。

5026007148dd2f4e68b6d404cea20653d9f3990b

把这个方案替换为纯 JS 方案（不要 jQuery）：https://stackoverflow.com/q/13437091/559676

@yixuan 有空不？要修改的模板文件在此：https://github.com/cosname/cosx.org/blob/master/layouts/partials/comments.html

**Comment by yixuan** [comment]
是不是点击“发表/查看评论”后再弹出评论页面？

**Comment by yihui** [comment]
点击按钮或者滚动到可见位置了自动加载都行。可能前者实现起来简单一些。

**Comment by yixuan** [comment]
搞定。https://github.com/cosname/cosx.org/commit/774d7652a9fc993ebafddfa971ca475be182eaca

**Comment by yihui** [comment]
非常好！能不能再发个 PR 把代码稍微打扫一下：iframe 的样式可以写入 custom.css，这样便于将来统一调整（样式与内容分离）；JS 代码可以写入 `static/js/comments.js` 然后引入，另外建议不要暴露所有变量为全局变量，这些代码可以包在匿名函数 `(function() {...})();` 里面运行，保持全局环境干净。大为之前的 JS 代码有同样的问题：https://github.com/cosname/cosx.org/pull/569/commits/12a8b06b96c4dc46f94e29d94dc81b8c1f59f1c6#diff-6cf15e00d819cbb3a3337b03dd641d8b

**Comment by yixuan** [comment]
没问题，这次是看没有加载评论所以急着收工，直接提交了。后面来弄这些，以 PR 的形式。

**Comment by yihui** [comment]
无妨。我并不介意直接推 master。

**Comment by Lchiffon** [comment]
我其实想说, 定义匿名函数再运行在R里面也可以做, 但是好像没流行起来的样子...

**Comment by yihui** [comment]
主要是怕污染环境。因为 JS 库用的越多，冲突的可能性越大，除非上重型武器，require 之类的。

R 里面都不需要匿名函数，`local()` 比 `function()` 可以少敲 3 个字母。
