### ISSUE TITLE
重写 2008-11-26-how-to-work-with-cos.md

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#58]
从 WordPress 换 R Markdown 了

**Comment by Lchiffon** [comment]
准备重写, 感觉投稿的情况好多:

1. 不会markdown -> 发邮件
2. 会markdown不会github -> 写好用github 网页提交
3. 会markdown会github -> 写好做PR
4. 会markdown有blogdown -> newpost+PR/网页

**Comment by yihui** [comment]
我最怕的其实是教 Windows 用户配置 GIT。这事情对我来说就跟解释什么是 PATH 环境变量一样。我稍微一想就会疯掉。

你可能还不如录视频更省事，我觉得上面每个情况录五分钟视频应该能说清楚吧。

**Comment by tomatoiscoding** [comment]
windows装个git bash就行 😈 快去录视频吧 @Lchiffon

**Comment by Lchiffon** [comment]
已发布
<https://cosx.org/2017/05/work-with-cos/>
