### ISSUE TITLE
论坛评论的 iframe

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#585]
有两个问题：

1. 手机上加载貌似很耗资源，我第一次加载的时候手机都死机重启了。所以要不要手机上就别自动加载了。

2. 滚动条有没有办法去掉？对不齐是硬伤。https://stackoverflow.com/q/16670931/559676

**Comment by yixuan** [comment]
滚动条我没太看懂，只用滚轮和触屏吗？

耗资源的问题我暂时还没有遇到过，Safari 吗？

**Comment by yihui** [comment]
对，Safari，我不知道是不是偶然情况。后来我再打开没有死机，但加载非常慢，所以我觉得手机上要么就别加载了，至少不要自动加载。

滚动条就是竖着的滚动条。这个滚动条的宽度大约在10像素左右，让人感觉评论区的右边和正文的右边不够贴近。不知道那个 flarum embed 插件能否再智能一点，做到跟 Disqus 类似。太费事就算了，这不算什么大问题。

![image](https://user-images.githubusercontent.com/163582/28195007-639601ce-680d-11e7-86e6-6962d114f424.png)

**Comment by yixuan** [comment]
Mac 上的 Safari 有加载问题吗？还是只有手机？我估计是跟 `onscroll` 事件有点关系，但要延迟加载只能靠这个吧。总之我再看看。

去掉滚动条估计不是什么难事，但去掉之后感觉也会有点怪，因为在评论区上滑动的时候主页面是不动的，滚动条相当于是告诉这里有个单独的页面，就像文章中嵌了一段长代码一样。要滚动主页面就会避免有滚动条的地方。

**Comment by yihui** [comment]
电脑桌面完全没问题。严格来说，滚动事件需要如此这般节流一下：https://css-tricks.com/the-difference-between-throttling-and-debouncing/ 但这个问题里的计算不太复杂，所以放纵一下也没关系。

滚动条去与不去确实都不对劲……

**Comment by yihui** [comment]
终极解决办法：

- 自动设置 iframe 高度为其内容窗口的高度：https://stackoverflow.com/a/819455/559676
- 但首先要解决跨域问题（据说 IE11 有幺蛾子，但谁会在乎 IE 呢）：https://stackoverflow.com/a/6046650/559676

**Comment by Gwill** [comment]
这个问题我们也遇到过，后来也想到谢大这里了，然后找了个库（ https://github.com/wistful/jquery-iframe-auto-height  ）解决了。

**Comment by yihui** [comment]
我真正倾向的方案是不用 iframe，而是直接用 Flarum 的 API 用 JS 直接发 GET 请求读取回帖得到 JSON，把它直接渲染在页面下面，回帖变成页面的自然子元素，这样就用不着各种暗黑的 iframe 处理技术了。这样做的坏处是不能直接在主站页面上回帖，而要点开论坛链接过去回帖。我觉得这个牺牲其实并不大，本来现在大家发评论的积极性就不太高了。
