### ISSUE TITLE
清理作者信息

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#592]
书接 #226 

现在所有人员信息都移动到了 https://github.com/cosname/cosx.org/blob/master/data/members.yaml

现在需要清扫一遍所有文章，确保作者信息都汇总到这个 members.yaml 文件中。

有些文章的作者信息缺失，如 https://cosx.org/2017/05/random-number-generation/ 需要补上。

有些作者信息包含在正文中，需要剥离，如 https://cosx.org/2017/01/deep-mining-users-r/

有的作者是统计之都，有的是 COS 编辑部，有的是 cos 编辑部，有的是 COS编辑部。如：https://cosx.org/2017/06/cos-interview-29/ 这些公共名需要统一一下。

合格的文章只是少数，如这两篇是我修订过的：

- https://cosx.org/2017/06/interview-fugee-tsung/
- https://cosx.org/2017/02/xaringan-presentation/

滚动到文章最底部，会看见作者信息自动生成在那里了，这是因为文章的作者的信息在 members.yaml 文件中可以找到。

**Comment by yihui** [comment]
这个事项还没有完全办完，比如我说的：

> 有些作者信息包含在正文中，需要剥离，如 https://cosx.org/2017/01/deep-mining-users-r/

还有严酷的魔王问题：https://cosx.org/members/

**Comment by Lchiffon** [comment]
这篇文章应该作者写成编辑部了, 作者信息我已经更新进去了

**Comment by yihui** [comment]
好，那先把谢佳标这篇的名字改了吧。还有魔王的名字也要改过来。
