### ISSUE TITLE
编辑和作者的个人信息

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#594]
网页：https://cosx.org/members/

所有人的信息存放在这个文件中，若有问题请编辑它：https://github.com/cosname/cosx.org/blob/master/data/members.yaml

#541 中那些还没提交个人介绍和头像的人，你们还在等轿子来抬咩。

---

技术问题：

@Lchiffon @tomatoiscoding 关于维护这个文件，我需要你们帮个忙，因为这里面有个超大的 Hugo 坑。Hugo 读这个文件时，不能保证这个列表的顺序，所以我加了一个 weight 项来硬指定顺序。问题是，当以后我们加新人时，这些 weight 值可能需要全体变动。我给的 weight 值是按照姓名拼音排序的，除了前四个人（主编、副主编）。我希望你们写个脚本（比如 R）做到：

1. 保留前四个人位置不动；

2. 后面的人按姓名拼音排序；

3. 有了顺序之后把所有人的 weight 值从 1 到 N 重新赋值。

这样每次加人就可以跑一下脚本，确保顺序。

这个 Hugo 坑我想了两个小时也没想好怎么避免，最后只能用这个笨办法了。

**Comment by fyears** [comment]
需要 `install.packages(c('yaml', 'pinyin'))`

坑：拼音转换比较慢，而且 `pinyin` 包有时候不准确。编码会不会有问题？反正我机上能识别中文和转换拼音和反输出到文件。

```r
# reweight-members.R

reweight = function(members, bosses_count = 4) {
    bosses = members[1:bosses_count]
    workers = members[(bosses_count + 1):length(members)]

    workers = workers[order(sapply(workers, 
        function(x){
            pinyin::pinyin(x$name, sep = '', method = 'toneless')
        }
    ))]

    members = c(bosses, workers)

    for (i in 1:length(members)) {
        members[[i]]$weight = i
    }

    return(members)
}


main = function(file_name = 'members.yaml', new_file_name = 'members.yaml') {
    members = yaml::yaml.load_file(file_name)
    new_members = reweight(members)
    writeLines(yaml::as.yaml(new_members), new_file_name)
}

main()
```

**Comment by yihui** [comment]
这个极好。

编码在 Windows 上八成会有问题，读应该没问题，主要是写文件的时候会有问题，可考虑用 `knitr:::writeUTF8` 写。

另外，`as.yaml(..., indent.mapping.sequence = TRUE)` 会对人类友好一点。

又及，`main()` 写出了 C 的赶脚。

**Comment by fyears** [comment]
强烈建议找个更准确的拼音包……我随手找的……

比如说，彭一般是指 peng 的，这个居然识别成更少见的 bang，把彭字排前去了……

**Comment by yihui** [comment]
我需要一个能保持输入顺序的数据结构，又要能很方便根据人名索引，反正我昨天试了两个多小时也没找到符合这两个条件的数据结构。Hugo 的模板编程有时候让人非常抓狂。

**Comment by Lchiffon** [comment]
windows下可以加个`writeLines`的参数, `useBytes=T`

此外, 这个里面包含了作者和编辑部成员的内容, 需要做区分么?
@PuddingNnn

**Comment by Lchiffon** [comment]
又及, 我看了下舰哥的`tmcn` 好像是同一个源, 彭也识别成`bang`

**Comment by yihui** [comment]
因为这个是如此之麻烦，我基本上打算重新调整一下数据结构了，争取去掉这个该死的 weight 值。

**Comment by yihui** [comment]
想好办法了，你们不用操心了。以后按名字拼音顺序排列就好了，不必使用 weight 值。
