### ISSUE TITLE
清理文章的附加信息

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#596]
需要把文章的附加信息移动到 YAML 元数据中的 `meta_extra` 选项中。示例：https://github.com/cosname/cosx.org/commit/8feddd398

这些信息会显示在文章标题下面的区域，效果：

- 整容前：https://5969a93b424ef2014bfb9cbe--cosx.netlify.com/2017/05/random-number-generation/
- 整容后：https://cosx.org/2017/05/random-number-generation/

**Comment by fyears** [comment]
这个能关闭了吧？

**Comment by yihui** [comment]
目前应该还没人把历史文章真的过一遍，我随便翻了一下，貌似还需要人来真正把这项工作做了，例如 https://cosx.org/2017/01/cos-interview-26-kouqiang/ 就还没动。

**Comment by tomatoiscoding** [comment]
哦，这个我认领。。。

**Comment by yihui** [comment]
感天动地 😭
