### ISSUE TITLE
新版页面R会位置不突出

### ISSUE THREAD

**Issue by Perfectizer** [cosname/cosx.org#600]
新版页面上R会相关内容只有在页脚处的“会议”，很不明显，会给想进站了解R会内容的用户造成困扰。相比之下，旧站页面上R会议的入口位置就比较醒目。建议可以在右上角加一个R会内容入口。

**Comment by yihui** [comment]
好的。我之所以犹豫，主要是因为“R 会议”是三个字，不整齐。但我觉得我们确实应该想个办法强调一下 R 会议。

**Comment by Perfectizer** [comment]
我觉得右上角加个入口是不是会比较好？

**Comment by yihui** [comment]
应该加。我的问题是文字用什么？

![image](https://user-images.githubusercontent.com/163582/28322369-8aa4eb9a-6b9b-11e7-85dd-819c11e6b9ea.png)

![image](https://user-images.githubusercontent.com/163582/28322410-a9203f34-6b9b-11e7-9586-b91ff0213b51.png)

**Comment by yufree** [comment]
类似 #566 拟将该处链接转到R会议官网
