### ISSUE TITLE
首页各文章标题展开样式优化

### ISSUE THREAD

**Issue by fyears** [cosname/cosx.org#603]
现在的情况是，长标题用了省略号，把鼠标移动上去时候自动展开。问题在于，展开的幅度很小，页面微微地摇晃，给人（我）带来晕船的微妙摇晃感觉。

强烈请求优化这个问题。。

issue 作以记录。

**Comment by yihui** [comment]
收到。谢谢。这是个很有挑战性的问题。大家都想想办法提提建议。

**Comment by Lchiffon** [comment]
![image](https://user-images.githubusercontent.com/7221728/28254865-7476a178-6ae3-11e7-96d7-111ec7983627.png)

我也不知道为啥, 只有在屏幕最大的时候才有这个bug

**Comment by yihui** [comment]
本苹果党无法重现这个问题。 @yixuan 可重现否？

**Comment by yixuan** [comment]
@Lchiffon 只有这个标题是这样还是其他所有多行标题都会？

**Comment by fyears** [comment]
@yixuan 诶我的妈，我这里也能重现。

Windows 下，chrome，正常屏幕下没有问题。按着 ctrl 用鼠标滚轮缩放之后到某一个大小后（50%）出现了同样的问题。

而且只有 ggimage 这篇出现这个问题！其它多行标题并没有问题。第二第三页的标题们也没有问题。。

**Comment by yihui** [comment]
所以我一直说要克制……浏览器能原生支持就最好，绿色纯天然，不能原生支持就需要慎重，毕竟是人工添加剂，用了之后经常是一坑未平一坑又起，非常能榨取程序猿小哥哥的精力。
