### ISSUE TITLE
增加一个返回上端的按钮

### ISSUE THREAD

**Issue by Lchiffon** [cosname/cosx.org#605]
这个功能考虑下？

对于手机用户， 我们的主页还是挺长的， 增加一个按钮可以一键返回顶端， 方便跳转啥的

比如[这个页面](http://langdawei.com/2017/01/07/leafletCN.html)底端的小火箭

**Comment by yihui** [comment]
好。最精简的方案应该是 `<a onclick="window.scrollTo(0,0);">返回顶端</a>`。

**Comment by yufree** [comment]
移动端确实长，但5年过去了，现在手机都有高刷大屏加持，快速手势滚动应该不再是问题了吧？
