### ISSUE TITLE
去掉所有文章的 description 选项

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#621]
我们不再需要这个选项了。去掉了免得大家再浪费时间去修改，如 https://github.com/cosname/cosx.org/pull/619/files

这个任务超级简单。小黄你来办了吧，算是报答轩哥处理你的晕船问题。 @fyears

**Comment by fyears** [comment]
pr 是有了，可是要不要斟酌一下，真的要删除？

~~万一以后又要改版呢🙄~~

**Comment by yihui** [comment]
就算改版，我也有了更智能的摘要提取办法，不怕不怕啦。Hugo 默认的提取方式弱爆了。退一万步讲，就算我们将来不用 Hugo 了，仍然有办法按现在的方式自动化提出摘要安回去。再退一万步讲，就算现在的自动化方法不够好，将来还有 `git revert` 的可能性。所以我的结论是我们是安全的。

**Comment by fyears** [comment]
那么谢大合并呗
