### ISSUE TITLE
关于搜索的建议

### ISSUE THREAD

**Issue by XueningZhu** [cosname/cosx.org#633]
似乎搜索还是比较常用的功能，关于搜索的问题/建议总结在这里，大家的用户反馈也可以加上：
1. 搜索需要单独跳转到一个界面后才能继续，能否直接在主页实现？ by Xuening
2. 作者信息检索不全：e.g., 主站搜索谢益辉，谢益辉的文章搜不出来 by Taiyun
...

**Comment by Perfectizer** [comment]
我这里搜索好像用不了。。。啥关键词都搜不出来><

**Comment by Lchiffon** [comment]
搜索好像有时候会失灵, 刷新下又好了, 我要确认下...

**Comment by Lchiffon** [comment]
哦, 发现这个bug是什么了, 写完东西按回车一点事情都没有, 按那个搜索的按钮就废了,.....

**Comment by tomatoiscoding** [comment]
我是写完东西按回车完全不管用，只能点搜索按钮才行 @Lchiffon

**Comment by fyears** [comment]
而我，有时候可以，有时候不可以。。。

console 里面有错误

```
Uncaught ReferenceError: search is not defined
    at HTMLButtonElement.onclick ((index):105)
```

这是踩 js 坑了吧。 是不是要 `document.ready()` 之类的

**Comment by yihui** [comment]
@Lchiffon 我好像忘了把搜索数据的生成模板搬过来了……这个还有用吗：https://github.com/cosname/cosx.org/blob/master/themes/hugo-steam-cos/layouts/archive_idx/single.html 还是说你的 https://github.com/Lchiffon/cosx-algolia 已经可以自动搞定一切了？

@tomatoiscoding 好问题。因为我们没有对搜索框 `<input/>` 绑定事件，只绑定了按钮的点击事件。这个应该加上。

@Perfectizer 结合你前一个问题 #634 来看，你的浏览器对 JavaScript 支持不太好。老实交代你用的是什么浏览器？IE 的话我们就友尽了。

**Comment by Lchiffon** [comment]
@yihui 已经用travis自动搞定一切了,  每天检查master分支有没有更新, 有更新就重新生成json文件上传algolia

**Comment by yihui** [comment]
@Lchiffon 完美得不能再完美。

所以就剩下第1个问题要解决了。我暂时没有精力想这事。
