### ISSUE TITLE
关于评论区的建议

### ISSUE THREAD

**Issue by Perfectizer** [cosname/cosx.org#634]
现在文章评论和文章本身是分开页面的，评论需要通过文章底部的链接进入。通常的评论（灌水聊天）倒是无所谓，但是涉及到文章内容的评论往往需要配合文章本身食用更佳，这样就会使得这种链接的方式用户体验不好（他们得翻回上一页去找对应的文章段落）因此，建议将评论区直接开在文章下方。。。

**Comment by yihui** [comment]
评论区目前就是自动展开在文章底部呀。可能你的浏览器有点老旧，某些 JavaScript 功能不支持？正常看到应该是这样的：https://cosx.org/2017/03/thoughts-on-insurance/

![image](https://user-images.githubusercontent.com/163582/28324888-199f4506-6ba2-11e7-987f-73e3210fb9a3.png)

**Comment by XiangyunHuang** [comment]
@Perfectizer 我发现这个问题已经解决了的，那我就关闭这个 issues 了
