### ISSUE TITLE
论坛管理分组

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#639]
我的建议是论坛后台管理组只分三组：普通用户、版主（闪电）、管理员（扳手）。不要再加新的组，不然又要陷入管理泥潭了，层级越多越耗神。放手让版主有权限管理**任意论坛帖子**即可，因为我们实在太缺人力。那种只有四个字的“新手求助”帖子标题实在是很伤我看论坛的热情，希望能有版主随手把标题改清楚了。

意下如何？ @yixuan

**Comment by yixuan** [comment]
去掉了多余的。

**Comment by yihui** [comment]
好，谢谢。
