### ISSUE TITLE
论坛标签短名建议

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#640]
尽量争取短小精悍，好记，打出来也好看。若能一个单词做短名，就尽量一个词；若一个词太长，可以用缩写（在不失意义的前提下）。若需要好几个词，也可以首字母缩写。

我的建议：

- 新鲜事：whats-new -> news
- 主站：main-site -> article
- 软件：software-misc -> software
- 综合：special -> general
- 人大统计：school -> ruc
- 开源：free-software -> open-source

其实我感觉单数可数名词用复数好像更恰当一点。如 cosx.org/t/job 看起来就不如 cosx.org/t/jobs 顺溜。

**Comment by yixuan** [comment]
新鲜事和主站我都改了，其他的是以前论坛的短链名，我觉得可以保留，万一以后有些重定向的锅可以接得容易些。其实标签名称没有那么重要（对于已经有的板块来说），毕竟帖子链接里不包含板块名，平时引用得不多。新设立的，想重点宣传和运营的标签可以好好想一下名字。

**Comment by yihui** [comment]
你说得对。标签名确实没什么实质的重要性，就是图个链接好看。重定向我只做了 R 语言版面的，剩下的都没管：https://github.com/cosname/redirects/blob/master/_redirects#L3-L10 改坏了也无所谓。

要不结合 #641 再考虑下？

**Comment by yixuan** [comment]
等我把数据库备份一下之后再动刀子吧。

**Comment by yihui** [comment]
好的，多谢！

**Comment by yixuan** [comment]
这几个都改好了，我就先关了。
