### ISSUE TITLE
论坛版面设置建议

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#641]
我觉得现在的版面结构分类不是特别匀称：

![image](https://user-images.githubusercontent.com/163582/28339104-9cf06ae2-6bd0-11e7-9041-cdafbb924736.png)

所有跟统计之都这个组织本身相关的应该归在一个大类“综合”里，包括公告、反馈、主站、COS 版主。九个大块里，我们自己的版块占了三个位置，感觉太多（只是从 https://d.cosx.org/tags 导航的角度来说）。

招生、就业、COS 项目建议归入“职业事业”大类（短名 career），变成它下面的小类。

留学保留，这下面将来还可以下很大一盘棋。

灌水、生活读书新知（建议重命名为读书）、文献归入“综合”大类，变成下属小类。

数理统计、生统（建议展开为生物统计）、经济、金融、精算、贝叶斯归入“统计学”大类，变成下属小类。

机器学习大类保留，因为热门。

保留 R 语言大类，因为是我们最重要的品牌。

剩下的 SPSS、SAS、开源归入“软件”大类。可视化也可以归进去作为小类，因为多数情况下都是涉及到软件相关的东西。

人大统计、华中科大归入高校。

所以最后的大类是：R 语言、新鲜事、统计学、机器学习、软件、高校、留学、职业事业、综合。

有些小类如果方便的话我觉得可以考虑移除或合并。例如开源可以并入软件。

何如？

**Comment by yihui** [comment]
@yixuan 先等一下哈，我数错了，有一些地方我想再调整一下。

**Comment by yihui** [comment]
好了。这事轩哥觉得嘛时候能办妥？这是我认为当前关于论坛的重要性最高的一件事。把这个事情理顺之后，接下来 COS 的一些工作就可以更方便展开了，比如蔡锐的海外沙龙、思喆（？）的高校计划等。

**Comment by yixuan** [comment]
今天我慢慢来整。

**Comment by yixuan** [comment]
我先做了一个实验，建立“职业事业”并把相关的标签并入这个分类：[https://d.cosx.org/t/career](https://d.cosx.org/t/career)。但可以看出来它并不会直接把相关的帖子放到这个类别中，而是在左侧菜单建立子菜单。我不知道这个是不是预期的效果，我理解的是把所有子类的标签全部打上父类的标签，这个可能得靠改数据库了。

**Comment by yihui** [comment]
对，要改数据库。

**Comment by yixuan** [comment]
有几个地方需要特别改一下，我大概还需要一些时间。

**Comment by yihui** [comment]
无妨。

**Comment by yixuan** [comment]
目测已经搞定了，所以就满足一下砍 issue 的手感，有坑再开。

**Comment by yihui** [comment]
赞。棋盘摆好了，接下来就要开始落子了。

**Comment by joegaotao** [comment]
统计学改成数据科学？感觉留学和高校似乎应该合并成一个“求学？，高校计划这个可以很大也可以很小，但我预期可能做不到规模宏大，还不需要一个大板块来支撑。沙龙会议都可以归到综合中。只是这样就成不了九宫格了

**Comment by yihui** [comment]
@joegaotao 统计学和数据科学对我来说都行，如果要赶时髦的话，改成数据科学也无妨。@yixuan 怎么看？

留学下面我想可以做这么几件事：一、COS 海外沙龙；二、海外高校分论坛（学术、生活都可以）；三、申请出国的相关服务（如修改 PS、咨询学校信息等）。

高校主要针对国内高校。能做多大要取决于我们能找到多少可用的人力种子。再就是看 @sunbjt 和 @Lingbing 的计划了。

沙龙、会议都可以变成小标签，跟大标签自由组合。比如一个帖子可以同时打大标签高校（或留学）和小标签沙龙。
