### ISSUE TITLE
用户和版主权限

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#643]
建议用户有如下权限：

- 发起报告（发起群众监督，不要只靠版主的眼睛）

建议版主有如下权限：

- 锁定主题（防止纠缠不清或一个问题下无限续问的人）
- 修改分类（纠正或补充帖子标签）
- 删除话题（防止广告垃圾）
- 查看报告

建议去掉版主如下权限：

- 永久删除回复
- 永久删除话题

**Comment by yixuan** [comment]
已设好。
