### ISSUE TITLE
帖子日期格式

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#644]
目前是 `3月 '10` 的格式，是否能改成跟更符合国人习惯的。或者像主站一样用 ISO8601 标准？YYYY-mm-dd

![image](https://user-images.githubusercontent.com/163582/28341203-3faf6380-6bd8-11e7-8486-ee18d3f98ed1.png)

**Comment by yixuan** [comment]
搞定。https://github.com/cosname/flarum-more-human-time

**Comment by yihui** [comment]
厉害！

**Comment by yihui** [comment]
不过 embed 插件貌似坏了……主站所有页面下的评论现在不能加载了。

**Comment by yixuan** [comment]
我大概知道原因，不是这个日期格式引起的。我正在看。

**Comment by yixuan** [comment]
这次是我的锅，已经修好了。
