### ISSUE TITLE
从 Markdown 一键微信排版的可能性

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#645]
我觉得一定有办法从 Markdown 文章一键转微信排版，以后就不必浪费小编的时间去仔细着一个个字排了。（从这个意义上来说微信也是人类进步的天敌）

随便放狗搜了一下，并没有深入研究：https://github.com/wizicer/wx-article-starter

期待哪位莽撞人出场，把这事儿给办了，应该可以节约编辑部几亿小时的时间。

**Comment by fyears** [comment]
谁有微信公众号后台的权限，又能写代码的？

~~当然是 @tomatoiscoding 师姐啦！~~

**Comment by Lchiffon** [comment]
我试了这个chrome 插件: markdown - here 

http://blog.sina.com.cn/s/blog_15151b1bc0102xtkv.html

内容复制进去, 一键转化, 可以编辑CSS样式,  但是图片需要手动上传

**Comment by yihui** [comment]
@Lchiffon 那已经很好了，所有文字排版自动化，图片手动上传也无妨，你是否有空闲把这事摆平？主要就是设计一个或几个大家比较认可的样式表。你可以跟 @yangggshuyi 合作，大家一致认为她的审美比较好。

有几个注意事项：

1. 文字上附着的链接需要转化为脚注（你可以凑合着用正则表达式试试）；

2. 公式如何处理我还不知道，理论上公式存在自动转图片的可能性。

**Comment by Lchiffon** [comment]
诶呀呀， 我回来了

话说图片这个问题挺伤的， 我问了下编辑部的小伙伴， 在图米的编辑器里面可以直接把图复制进去， 再复制到微信里面（公式也可以）

但是如果有这个工具，图片要一张张传， 公式也是

所以我觉得如果图片的问题不能解决，这个功能还是有点鸡肋的

**Comment by yihui** [comment]
图米编辑器支持直接从网页全文复制粘贴吗？我的意思是一键复制粘贴所有文字和图片。

**Comment by Lchiffon** [comment]
支持....

**Comment by yihui** [comment]
唉。即使这样，那应该也比目前的排版省事多了。

祝微信早日垮掉，省得浪费众生的时间。

**Comment by XiangyunHuang** [comment]
-  [x] 长链接转短链接，比较适合统计月度的文章排版，如  http://sina.lt/
-  [x] Markdown转微信文章，如 https://github.com/lyricat/wechat-format 能解决大部分格式问题
-  [ ] 插入图片和公式

**Comment by XueningZhu** [comment]
如果能搞定 那就太牛了！

**Comment by XiangyunHuang** [comment]
1. 如果文章中存在大量的 LaTeX 公式，手动挨个转 PNG 图片，**复制粘贴的工作量比较大**
1. 类似地，如果文章中图片比较多，手动给图片转码，**复制粘贴的工作量比较大**

**Comment by yihui** [comment]
公式存在自动转图片的可能性，不用手工复制。图片转 base64 码是更简单的事（如 `knitr::image_uri()` 或者 Pandoc），只要微信支持 base64 码。

**Comment by XiangyunHuang** [comment]
@badbye 又发现一个微信排版工具，目前看来功能是最全的，网址 https://md.aclickall.com/#h

**Comment by LingrenKong** [comment]
汇报一下目前的微信排版方案，解决方案mdnice

- 工具部分使用免费（网页端编辑和Chrome插件免费）
- 支持数学公式渲染（知乎公式、微信自动粘贴SVG导出）
- 免费使用其图床工具
- 支持定制CSS，还需要有人帮忙写一个，目前是用提供的模板加手动小修颜色以适应暗色模式

https://www.mdnice.com/
