### ISSUE TITLE
论坛翻页

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#649]
我个人不是特别喜欢无限加载的功能，不知道是否有可能替换为古老的页码翻页方式。

无限加载的最大问题是戳了半天看到了想看的帖子，点进去一看，再后退回去就会死人，因为后退不能保持之前看到的位置。要是之前往下加载了十页，那又得重新点十次。

**Comment by yixuan** [comment]
为什么我后退可以回到原来的位置？而且侧边栏也可以快速导航的。我觉得实现页码的可能性不大，所有的内容都是动态和延迟加载的。
![untitled](https://user-images.githubusercontent.com/216398/28424563-f16c2f90-6d3b-11e7-880e-d5e2f5011808.png)

**Comment by yihui** [comment]
哦，好的。确认后退确实可以保持原来的位置。那这个事项就更不紧急了，页码唯一的好处是避免浏览器里加载无限多的内容太耗客户端资源。谢谢！
