### ISSUE TITLE
主站的微信分享图片

### ISSUE THREAD

**Issue by Lchiffon** [cosname/cosx.org#654]
直接把主站分享到微信上, 链接默认是没有图片的....
是否要增加这个DOM让分享的时候有图图呢
`<div id='wx_pic' style='display:none;'><img src='/wx_share.png'/></div>`

我略倾向于不加, 但这的确是个问题...

**Comment by fyears** [comment]
为啥不加？图片用 logo 就好了？

**Comment by yihui** [comment]
是个问题。但微信竟然用这么暗黑的手段提取图片？？没有 `<meta>` 或 `<link>`之类的方式？本来我对微信的评分都已经负一万八千分了，如果真的只能这么干，那我只能借郭德纲的一句话对微信说：死~~~去~~~

**Comment by Lchiffon** [comment]
https://www.zhihu.com/question/21668601

**Comment by yihui** [comment]
在那知乎页面上看了一大堆链接，仍然没明白到底该怎么弄。貌似是没这么简单。

**Comment by yufree** [comment]
主站已被微信拉黑 🐶
