### ISSUE TITLE
数学公式中存在多余的`$`符号

### ISSUE THREAD

**Issue by szcf-weiya** [cosname/cosx.org#655]
[随机数生成及其在统计模拟中的应用](https://cosx.org/2017/05/random-number-generation/)一文中，数学公式中存在多余的`$`符号。
如
![selection_488](https://user-images.githubusercontent.com/13688320/28369245-9d7e467e-6cc9-11e7-9389-dc78ecaf2a0f.png)
![selection_487](https://user-images.githubusercontent.com/13688320/28369247-9e35c07e-6cc9-11e7-8646-0c67fe7f39a6.png)

**Comment by yihui** [comment]
多谢指出这个问题！这是我的代码的缺陷，已经在这里修正：https://github.com/yihui/hugo-lithium-theme/commit/d01e4a3170f5c2b0b17e0c540c3344bbcefd33e9

现在这些数学公式应该都可以正常渲染了。
