### ISSUE TITLE
论坛代码高亮不支持R

### ISSUE THREAD

**Issue by yixuan** [cosname/cosx.org#666]
需要我们自己生成一个包含 R 的 `highlight.js` 文件，然后让论坛链接过去。或许可以放到主站的 js 库去？@yihui

**Comment by yihui** [comment]
如果需要自己定制一份 highlight.js 的话，就传到 https://github.com/cosname/uploads 吧。主站用的是 BootCDN：https://github.com/yihui/hugo-xmag/blob/412c059171/layouts/partials/footer.html#L23-L28

**Comment by yixuan** [comment]
https://github.com/cosname/uploads/commit/9a25907c837af96fd10ed9c5ebdc312555f48405 https://github.com/cosname/flarum-post-formatter/commit/a41502988b7963e0aca3d4f75adc3d141d686838 搞定。

**Comment by yihui** [comment]
666
