### ISSUE TITLE
论坛似乎还在支持 BBCode

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#668]
例如 https://d.cosx.org/d/419221 帖子中的下标 `[i]` 被解释为斜体了。我看后台并没有启用 BBCode 呀。这是咋回事？

BBCode 这种弱鸡标记语言还是表支持为好。

**Comment by yixuan** [comment]
BBCode 是我写在插件里的，因为以前的帖子需要用到。新手教程里面我已经刻意回避掉了。

**Comment by yihui** [comment]
哦，要是能对新帖子禁用就好了。因为 `[i]` 实在太常见了。

**Comment by yixuan** [comment]
代码中的都会被保护，像那个帖子我重新编辑了。

**Comment by yihui** [comment]
嗯，我知道，我只是略担心将来老是要编辑这种帖子，不过要是版主队伍足够大，应该也可以应付。
