### ISSUE TITLE
下载并优化所有外链图片

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#671]
包括上传到 Github 的图片。尤其是 PNG 图片严重需要优化，可用 optipng。Google 目前对 cosx.org 在优化方面的评分为 15 分（满分 100），主要就是因为图片巨大，而且又有巨大的优化空间。

这些图片可以放到 https://github.com/cosname/uploads 也可以新建一个库（uploads 库本身已经够大了，我怕 Netlify 会不高兴）。

**Comment by fyears** [comment]
这个是做了？关了吧？
