### ISSUE TITLE
COS访谈标签无法显示2017年后的文章

### ISSUE THREAD

**Issue by joegaotao** [cosname/cosx.org#672]
点击cos访谈标签后，进入[cos访谈](https://cosx.org/categories/cos%E8%AE%BF%E8%B0%88)，无法显示2017年后的文章，其他标签貌似正常

**Comment by yihui** [comment]
这是因为有的大写 COS 有的小写 cos。应该统一大写。

@tomatoiscoding 应该会处理 #609 谢谢报告这个问题！

**Comment by tomatoiscoding** [comment]
来背锅了
