### ISSUE TITLE
重启个人博客项目以及聚合博客项目

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#673]
虽然 blog.cos.name 死了，但我仍然不死心。等我下一次有足够的空闲的时候，我想把过去没推起来的个人博客项目再推起来。

要问为什么的话，就一句：我愣是不服微信，忍不了这么落后的工具统治世界。

**Comment by XiangyunHuang** [comment]
于主编 @yufree  的博客聚合项目 <https://github.com/yufree/daily> 相关联的讨论 https://github.com/yufree/daily/issues/17

@yihui 博客聚合项目有些啥子要求

**Comment by yihui** [comment]
没啥子特别要求，于主编做的已经很好了，有个能从 RSS 自动更新的日志列表就够了。现在更大的问题可能是已经没几个人写中文博客了，所以这个聚合博客最后可能跟统计没啥关系，纯属个人博客圈。英文博客还有点希望。

**Comment by yufree** [comment]
目前解决方案为通过[论坛](https://d.cosx.org/d/421538)收集博客，然后用 Daily RSS 进行聚合，如有新方案会重开本 issue。
