### ISSUE TITLE
支持自定义代码高亮语言

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#677]
例如 Julia https://github.com/cosname/cosx.org/pull/657#discussion_r128987248

其实这个应该可以自动化。在 Hugo 模板中用正则表达式查找 `.Content` 里的 `<code class="language-([^"]+)">`。但匹配出来的语言需要跟 highlight.js 支持的语言做一个交集。

**Comment by fyears** [comment]
现在 20170818 主站还是使用了 BootCDN 的版本，而不是 https://github.com/cosname/cosx.org/issues/666 即
 https://github.com/cosname/uploads/commit/9a25907c837af96fd10ed9c5ebdc312555f48405 的版本。uploads 的版本是有 julia 支持的。要不要改一改？还是说故意不改的。。？

此外真的要任意语言支持，不需要如此复杂倒腾 hljs，直接 [server side rendering](https://gohugo.io/tools/syntax-highlighting/#server-side) 不好吗？

**Comment by yihui** [comment]
代码高亮问题不太重要，所以有空再折腾吧，现在能支持主要的语言外加 R 就差不多了。我个人不是特别喜欢在服务器端生成高亮代码，因为我希望 HTML 能尽量干净一点。

**Comment by fyears** [comment]
那就先把主站的切换成uploads版本的hljs得了，那个已经有了julia

**Comment by yihui** [comment]
很不幸我把 highlight.js 写死在 Hugo 模板中了。我目前还没有内存去处理这件事。只要这事不是让你焦躁异常，就先往后放放吧。
