### ISSUE TITLE
微博自动推送

### ISSUE THREAD

**Issue by Lchiffon** [cosname/cosx.org#678]
不知道这个靠谱不, 每次更新文章自动推送微博

还有还有自动配图~

还有还有把最新论坛消息也更新到微博~

**Comment by Lchiffon** [comment]
此处
@qinwf 
rweekly好像有做微博推送

**Comment by yihui** [comment]
据我昨夜看的消息，组织上好像安排给 @Autumnthinker 了？自动推送总是缺人情味。像我就非常不喜欢敝司的 R Views 自动推送。感觉还是有个活人写点有智力迹象的人话手工发微博比较好。

**Comment by Lchiffon** [comment]
这样呀~知道了, 那我先关了~

**Comment by qinwf** [comment]
rweekly 微博推送用的是 IFTTT，前段时间好像微博严打，rweekly 的微博就被封了，到现在还没有解封。。。不知道是不是用 IFTTT 的原因。

**Comment by Lchiffon** [comment]
:rofl:
