### ISSUE TITLE
新的审稿指南

### ISSUE THREAD

**Issue by XueningZhu** [cosname/cosx.org#684]
需要参考投稿指南写一个审稿指南，请 @Lchiffon @tomatoiscoding 两位拟一份，起点是作者已经将文章提交github；需要包含一些github操作，辛苦两位

**Comment by yihui** [comment]
啊呀，主编开始指定任务到人头了，而且还开始加标签了。喜极而泣！😂

这个审稿指南在编写过程中可以参阅一部分以往合并了的 PR 里的审稿意见，把常见问题总结出来。

**Comment by PuddingNnn** [comment]
@yihui 我刚看见你帖子说最好加入小黄><，所以我又加入了小黄同志 @fyears ，小黄同志你的名字肿么不是你的真名，还好我没失忆；这篇文章请 大为 或者 蓓蕾 主笔，请小黄补充

不知道为啥每次上论坛都要翻越长城……我昨天刚邀请了一批狗熊会人才计划学生去论坛提问活跃啥的，结果发现论坛访问很不稳定……还好我告诉他们要科学上网

**Comment by yihui** [comment]
@fyears 要是你不介意的话，麻烦设置一下自己的 Github 名字吧，这样 @ 起来方便自动补全，省点记忆。

@PuddingNnn 唉。那我们启动网站备案进程把网站搬回朝中吧……我担心的是被有关部门要求所有论坛用户提供手机号。

**Comment by PuddingNnn** [comment]
@yihui 嗯嗯
备案的事情，是否之前是CFO在跟进？ @dengyishuo 不知是否有个建议流程 编辑部可以出人配合哈

**Comment by yihui** [comment]
@PuddingNnn 这事我发论坛了，舰哥可能可以搞定，但我这边略有些技术麻烦，我还没想好怎么解决。

**Comment by fyears** [comment]
雪宁姐在 https://github.com/cosname/cosx.org/pull/657#issuecomment-322293319 问审稿指南在哪里，两位大佬们 @Lchiffon @tomatoiscoding ，催稿啦！

另，我的那部分散落在 https://github.com/cosname/cosx.org/issues/597 里。

**Comment by fyears** [comment]
在 @yihui @PuddingNnn  的不断催稿之下， @Lchiffon  起了个头，我终于整理了一份审稿指南的初稿了。（嘤嘤嘤） 还有，啊，边总 @tomatoiscoding  给了精神上的鼓励和支持。。。

详情见以上交叉引用了的 pr https://github.com/cosname/cosx.org/pull/716 。

为了统一讨论，不再分散内容，请大家尽量集中在这个 issue 和上述 pr 里面进行讨论。。。

大家对文章已有的内容有什么需要修改的话，请在 pr 里面相关词句添加评语（这可是：**对《审稿指南》的审稿！**哈哈！）。有什么其余要想说的（比如说催稿），请在这个 issue 里提出。

文章篇幅最大的是我们之前在各个 issue 里提及到的文字格式。此外是大为截图了 GitHub 操作。还有就是我们三个之前略微讨论过但是没有详细谈论的“进阶审稿“部分。大家请踊跃总结一下。

此外，写完了之后，才发现这个和编辑指南有很大的重叠之处。这个我不知道该怎么处理，因为不是很清楚各位小编的操作流程。

**Comment by fyears** [comment]
pr 已经被 merge。
