### ISSUE TITLE
消息小铃铛计数不正确

### ISSUE THREAD

**Issue by hengqujushi** [cosname/cosx.org#685]
如图，消息数出现了负数

![untitled](https://user-images.githubusercontent.com/163582/28681113-025b5632-72be-11e7-91a3-cae3a8672509.png)

**Comment by yihui** [comment]
小伙砸，截图要看一下内容哈。已经给你抹掉了不该截的部分。

我也发现计数有时候不太准确，尤其是在手机上看帖的时候。不过我觉得这问题不太重要，而且我估计我们也没这个能力和精力去修正它。

**Comment by hengqujushi** [comment]
sorry；是，我发完也觉得没那么重要。

**Comment by yihui** [comment]
没事，先扔这儿吧，万一什么时候 Flarum 出了正式版顺带把这问题解决了呢 😁
