### ISSUE TITLE
论坛字体 Open Sans 无法加载

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#690]
打开浏览器控制台就能看到。

![image](https://user-images.githubusercontent.com/163582/28764532-7d9f8532-758b-11e7-891b-df1247ac8b68.png)

网络字体默认情况下是不能跨域的，一个域名不能调用另一个域名下的字体。

要么去掉这个字体，要么换别的方式加载。墙内应该有字体 CDN，但我还没发现稳定好用的。

**Comment by yixuan** [comment]
发现 Flarum 有个专门放字体的文件夹，就转到那儿去了。
