### ISSUE TITLE
论坛还缺一些英文词句的翻译

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#695]
我目前注意到的：

我报告了帖子分类不当，`off_topic` 没有翻译：

![image](https://user-images.githubusercontent.com/163582/28833414-e2ca73c6-76a4-11e7-8494-91ddc2164411.png)

后台这里没有翻译：

![image](https://user-images.githubusercontent.com/163582/28833456-feb6ed4e-76a4-11e7-8f0c-fca41dded399.png)

**Comment by yixuan** [comment]
最近的一次更新应该已经解决了。
