### ISSUE TITLE
我要这图例有何用

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#698]
可以写一篇几百字的短文：https://d.cosx.org/d/417769 事情很简单，但小编要好好想想：

1. 什么情况适合用颜色图例；

1. 什么时候适合横着放条形图；

1. 什么时候适合竖着放条形图；

1. 这图在目前的最终方案上是否还有改进空间（例如点图如何）；

1. 是否可以扯到 Cleveland & McGill 总结的[感知原则](http://info.slis.indiana.edu/~katy/S637-S11/cleveland84.pdf)以及后人 [Jeff Heer 的众包试验](http://vis.stanford.edu/files/2010-MTurk-CHI.pdf)上；

等等。请 @PuddingNnn 安排，并请小编大开脑洞。

**Comment by PuddingNnn** [comment]
第一个图简直辣眼睛……
@MikeLYX 宇轩负责来写 人才计划被训练哭了吧 条形图的作图规范 我觉得你略有心得  你如果想扯上其他图 我也不拦你

**Comment by yihui** [comment]
要是还没哭的话，我可以帮忙压榨，保证哭得痛快 😂

**Comment by Cloud2016** [comment]
@PuddingNnn 确实，
@yihui  第四点，在类别标签比较多的时候用点图，举例如下（反例就不画了，条形图都会挤一块）
![dotplot](https://user-images.githubusercontent.com/12031874/28908020-c4770c08-7853-11e7-90c7-55cf496480dd.png)

**Comment by yihui** [comment]
@Cloud2016 你可以考虑跟 @MikeLYX 合写这篇文章。

**Comment by Cloud2016** [comment]
@yihui 很荣幸，我试着多举例子。再来一个：
类别标签是数字，还是可以正着放，如<https://cosx.org/2017/05/random-number-generation/>，下面只考虑一个图不做对比
![hist_plot](https://user-images.githubusercontent.com/12031874/28908283-6493aff6-7855-11e7-97df-34f13da0d34d.png)

**Comment by Cloud2016** [comment]
下面这几个图，是临时从电脑里翻来的，虽不是barplot，但是想表达的意思一样，再提三个点：

6. 为了表达某种关键信息，一定要上色，图例也相应地需要
![img1](https://user-images.githubusercontent.com/12031874/28908702-9ac4e53e-7857-11e7-8ea1-ef225c20bec8.png)
![img2](https://user-images.githubusercontent.com/12031874/28908725-b5ae8350-7857-11e7-9862-998be4fdf160.png)


7. 复杂（多个）图例怎么搞，这个ggplot2搞得好，我这里没有使用ggplot2（这里把某个图例分面了），就是说图例和分面可以处理多个图例

![img3](https://user-images.githubusercontent.com/12031874/28909045-57fe4428-7859-11e7-98b4-affe179bab53.png)


8. 要不要上色，上什么色

![img4](https://user-images.githubusercontent.com/12031874/28909173-e43dd5f2-7859-11e7-8b16-c0701878a657.png)

**Comment by Cloud2016** [comment]
正例，为了对比，要上色，图例相应地加上
![bed_net](https://user-images.githubusercontent.com/12031874/28909799-8cc84412-785c-11e7-8307-4b4c5131f4a2.png)

**Comment by Cloud2016** [comment]
来自MATLAB的样例
![img1](https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/35274/versions/3/previews/html/Bar_Plot_3D_01.png)
还有这
![img2](https://cn.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/52067/versions/1/screenshot.jpg)


哼，怎能没有R版<http://www.cpwardell.com/2015/08/28/legoplots-in-r-3d-barplots-in-r/>
![img3](http://www.cpwardell.com/wp-content/uploads/2015/08/cpw_context_transparent.png)

这个3D图，也是魔性，上了nature <http://www.nature.com/ng/journal/v45/n5/full/ng.2591.html?foxtrotcallback=true>
![img4](https://images.nature.com/full/nature-assets/ng/journal/v45/n5/images/ng.2591-F1.jpg)

**Comment by Cloud2016** [comment]
单从画图的角度看，我觉得条形图也是通着直方图的，下面几个是直方图，但是像极了条形图
请看<http://www.pnas.org/content/111/41/14722.figures-only>，现引一个看看
![img5](http://www.pnas.org/content/111/41/14722/F2.medium.gif)

**Comment by Cloud2016** [comment]
如果把此图里的柱子躺着，又有点像ggjoy的山峦图
![img1](https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/35274/versions/3/previews/html/Bar_Plot_3D_01.png)
请比较
![ggjoy](http://austinwehrwein.com/data-visualization/it-brings-me-ggjoy_files/figure-html/unnamed-chunk-3-1.png)

**Comment by Cloud2016** [comment]
我这里画了三张图以飨观众
![airlinepassenger_ _1](https://user-images.githubusercontent.com/12031874/28929250-1b503664-78a2-11e7-9119-6dde6255ae63.png)
![airlinepassenger_ _2](https://user-images.githubusercontent.com/12031874/28929261-212cff04-78a2-11e7-88c9-f2c1389ca15a.png)
![airlinepassenger_ _3](https://user-images.githubusercontent.com/12031874/28929269-252ff66a-78a2-11e7-8a80-2c43cec5959d.png)

**Comment by MikeLYX** [comment]
好滴，之前我想到的只是二维条形图，师兄把我的思维由二维条形图开阔到了三维，个人感觉三维里上颜色的很多都是有渐变色的效果，这和二维的有很大区别，二维条形图中的渐变色好像很少看到，在多个分类中才可能会出现，比如师兄之前引用过的这张图里的图b就是这样：

![二维条形图](https://camo.githubusercontent.com/7b867bcbf8653d3d4c80f4d3302362309944af2d/68747470733a2f2f696d616765732e6e61747572652e636f6d2f66756c6c2f6e61747572652d6173736574732f6e672f6a6f75726e616c2f7634352f6e352f696d616765732f6e672e323539312d46312e6a7067)

或者渐变色是用在颜色表达除却纵坐标外的另外一种信息，比如这样:

![二维条形图2](https://github.com/MikeLYX/picture/blob/master/some%20described%20picture/picture1.png?raw=true)

**Comment by Cloud2016** [comment]
嗯嗯，乍一看还以为颜色越深代表价格越高，原来是表示第三个量，但是一般倾向颜色越深代表的数量越多，这里图例的颜色反了。我之前只注意到3维的柱形图了，旁边竟然有个复杂的条形图案例

**Comment by Cloud2016** [comment]
@MikeLYX 这里有个柱形图（条形图）的集合 <http://gnuplot.sourceforge.net/demo/histograms.html>，我觉得里面有些不错的思路

**Comment by MikeLYX** [comment]
@Cloud2016 同意师兄说的正反例问题，我觉得这么写的确有必要

师兄给的那个集合非常有趣啊，看上去都有一些几个图进行对比的架势，那我说说我的想法：前两张柱状图是gap的区别，我觉得第一个比较好，显得比较饱满，整个画面也不是特别空，第二个就显得空了；

中间那三张最有意思了，同意师兄说的“堆的有点多了就不适合堆积这种方式了”，，三张图不知道重点是啥，感觉就算有也很不起眼...，再加上颜色多，真的亮瞎眼...而且这三张有的国家选的颜色竟然还有特别相近的，完全不知道哪个是哪个

最后这两张在我经历了中间三张的摧残之后就显得非常赏心悦目了，最后那张堆积柱状图我觉得还不错，主要好在三点：一点是堆积的少，颜色变化也大，能看清楚；第二点是它相当于多加了一个地区的分类归组，可以再进行一些有趣的研究，这两点都是比中间三张图好的地方；第三点是由于横坐标太多了，这样一个横坐标对应一个柱子还是容易看的，像他前面那个分类柱状图，我看一会绝对就不知道哪个柱子对应的是哪个decade了...

另外有个小问题，图里数量级上6的纵坐标都是科学计数法，没到6的就直接是数字，这个是否有明确规定，或者说系统设定？

**Comment by Cloud2016** [comment]
赞这波分析，科学计数法怎么好看怎么来，有时候某人为了凸显这个数量，故意搞一大堆零，不然应该科学计数法，将坐标取对数也是常用操作

**Comment by Cloud2016** [comment]
我来画图，你组织语言好不好？ @MikeLYX 

## 正立条形图

泊松分布

<img src="https://user-images.githubusercontent.com/12031874/29483578-d90c9658-84db-11e7-85c9-d44db8994d33.png" width="60%" />

国际航班乘客

<img src="https://user-images.githubusercontent.com/12031874/29483579-dda5eafc-84db-11e7-8728-0fb133189208.png" width="60%" />


## 横躺条形图

各类癌细胞数目

<img src="https://user-images.githubusercontent.com/12031874/29483580-e1aef85a-84db-11e7-95ac-860d3c05879c.png" width="60%" />


## 堆积条形图

1940年弗吉尼亚州各年龄段死亡率（单位千分之一） 

<img src="https://user-images.githubusercontent.com/12031874/29483581-e44f0cee-84db-11e7-9b72-52b12b66cd11.png" width="60%" />

## 复合条形图

1973年加州大学伯克利分校最大的六个系学生录取情况

<img src="https://user-images.githubusercontent.com/12031874/29483635-15bb4ac6-84dd-11e7-9c63-e36ef69a9eb5.png" width="60%" />

## 点图

1974年美国汽车趋势杂志报道的车型、气缸数和每加仑里程的关系

<img src="https://user-images.githubusercontent.com/12031874/29483586-eac14880-84db-11e7-80f3-5bfa593a34d3.png" width="60%" />

**Comment by MikeLYX** [comment]
好的！我8月22号前就把这篇文章完整写出来，交给师兄查阅，在此立下字据！

**Comment by MikeLYX** [comment]
@Cloud2016 我先在自己仓库建了一篇文章，麻烦师兄看一下~我打算咱们两个先把文章意见统一后再发到COS

**Comment by Cloud2016** [comment]
@MikeLYX 文章内容还没细看，我把参考文献先加上了。

**Comment by Cloud2016** [comment]
@MikeLYX 我修改了一波，把R代码添加在你的repo下，你看看还有没有其他问题

**Comment by fyears** [comment]
对应于 https://github.com/cosname/cosx.org/pull/713 ？手动关联一发。

**Comment by Cloud2016** [comment]
@yihui 这个 issue 可以关了
