### ISSUE TITLE
ggjoy图写作

### ISSUE THREAD

**Issue by XueningZhu** [cosname/cosx.org#699]
请 @dubuyh  负责写作：
https://d.cosx.org/d/419270-ggjoy

辛苦辣！

**Comment by dubuyh** [comment]
收到！8.20之前准时交稿(●'◡'●)

**Comment by yihui** [comment]
算 👍

**Comment by fyears** [comment]
这个，嗯。。。是不是跳票了。。

**Comment by yihui** [comment]
作为一个经常跳票几年的人，这篇文章跳票三个月我也没意见，看作者自己时间安排吧。

**Comment by yihui** [comment]
不然换掉算了？https://yufree.cn/cn/2017/10/23/joyplot/

**Comment by dubuyh** [comment]
啊啊啊啊，我之前快写完了被别的事情搞忘了😭我清明之后把它写完，大佬们看看能不能用？

发自我的 iPhone

**Comment by PuddingNnn** [comment]
@yufree 似乎已经总结非常全面了 能否直接总结成投稿
@dubuyh 你之前写的能总结到这里面吗

**Comment by dubuyh** [comment]
哦哦，已经有别人写了呀，那就用yufree总结的叭，我之前也是觉得写得太简陋了会没投

发自我的 iPhone

**Comment by yufree** [comment]
投稿没问题，但有个问题不好办，最原始来源那个博士论文上脉冲星的图我没有版权，按《科学美国人》的版权指示需要询价且最长展示期12个月，我可以替换成原文连接，但这样前半部分图片就比较单薄了。
