### ISSUE TITLE
首页时间不对

### ISSUE THREAD

**Issue by szcf-weiya** [cosname/cosx.org#706]
![image](https://user-images.githubusercontent.com/13688320/29375081-59f303b2-82e6-11e7-99af-304e7d16abc0.png)
如图,现在为8月17号, 但首页时间为8月14号 (确定不是缓存原因, 多次刷新了)

**Comment by yihui** [comment]
那里显示的是最后一次编译网站的时间。不过你可能是对的，显示当前日期貌似更合理。

**Comment by szcf-weiya** [comment]
@yihui 原来是这样.

**Comment by yufree** [comment]
在主站layout中添加“最近更新：”

**Comment by XiangyunHuang** [comment]
我在 PR https://github.com/cosname/cosx.org/pull/1051 加了点文字「最近更新于」

<img width="1257" alt="截屏2022-07-03 11 35 32" src="https://user-images.githubusercontent.com/12031874/177023464-58476f25-6931-4bd5-9adb-a8cee4d0eac6.png">
