### ISSUE TITLE
列表页公式问题

### ISSUE THREAD

**Issue by Lchiffon** [cosname/cosx.org#718]
![image](https://user-images.githubusercontent.com/7221728/30191636-bc84c070-9474-11e7-83da-72f45d4f6ca4.png)

https://cosx.org/tags/%E5%9B%A0%E6%9E%9C%E6%8E%A8%E6%96%AD/

捉到虫子一只, 谢大大来看看咋回事...
@yihui

**Comment by yihui** [comment]
某种程度上这也是故意的，列表页面我没有加载 MathJax，主要是为了首页加载速度快一点。摘要里面的数学公式也许不那么重要。

**Comment by fyears** [comment]
我也同意不加载。唯一的顾虑是读者会不会认为这是一个 bug 而不是 feature。。

**Comment by yufree** [comment]
暂不加载
