### ISSUE TITLE
此帖有毒！只要我去编辑，页面就无响应

### ISSUE THREAD

**Issue by Cloud2016** [cosname/cosx.org#721]
帖子位置 <https://d.cosx.org/d/419455-r-pomp>

<img width="351" alt="pomo" src="https://user-images.githubusercontent.com/12031874/30237014-e1f39bd8-955a-11e7-9f4b-2fb58ce43f18.png">

**Comment by yihui** [comment]
我可以重现。不知道是不是 Markdown 问题或者有好几个代码块的原因，这篇帖子的代码格式看起来很混乱。抄送 @yixuan

**Comment by yixuan** [comment]
我暴力改了，具体原因布吉岛，我也很无奈……
