### ISSUE TITLE
主站文章的链接为啥仍然忘了发论坛？

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#739]
如：https://d.cosx.org/d/419508

这事我清楚记得我以前已经在 Github 上提醒过一遍 @Perfectizer 同志了。

凡是需要反复提醒的事情都说明我们的流程有问题，而不是人上不上心的问题。我们的编辑部指南（ https://cosx.org/reviewer ）里能否给一个用来打勾的清单？每一篇文章都严格按照步骤一二三四来走。这个论坛帖子问题应在最后几步中了，没打完勾的文章不能发布。类似于（我随便写的，不完整）：

- [ ] 主编安排审稿人
- [ ] 审稿、修改
- [ ] 文字编辑做校对工作
- [ ] 论坛帖子负责人发帖并提供 `forum_id` 加入文章
- [ ] 微信编辑
- [ ] 合并 PR，发布文章
- [ ] 论坛帖子负责人更新帖子中的主站文章链接

每个 PR 里的第一楼都放上这个清单，一步步走流程。看谁还能再忘了。

@PuddingNnn @tomatoiscoding @Lchiffon @fyears

**Comment by PuddingNnn** [comment]
确实是这样……这个建议很好，没问题

**Comment by Lchiffon** [comment]
除了更新编辑部指南以外, 是不是可以把这个写成一个新建PR的模板, 再加上作者留联系方式, 以防失联

另外, 是不是需要增加一个是否接收投稿的流程, 之前出过一些稿件不符合要求被毙的例子

**Comment by fyears** [comment]
此外，还是觉得需要自动化。。

**Comment by yihui** [comment]
@Lchiffon 这个 PR 模板的提议很好，请动手吧。

@fyears 放码过来。

**Comment by Lchiffon** [comment]
#740

**Comment by fyears** [comment]
忽然间想明白了这玩意该如何运行：自动化跑去论坛加一个帖子太激进了，但是我们至少可以加上一个 pr check。有谁知道这个 api 在哪里吗？

我说的是这种：

![pass netlift check](https://user-images.githubusercontent.com/1142836/31731817-cec9b4b6-b468-11e7-863d-1ae578fb4994.png)

比如说现在用上了 netlify，它就是加上了一个 check，如果没有通过 netlify 编译的话，我们自然就知道不能 merge（或者设定上无法 merge）。

理想状态下：一个 python 脚本或者什么东西，每次 pr 的 commit 过来都跑一次检查是否通过了以上设定，直到上述 n 个 todo 都通过了，这个 check 才通过。拍脑袋猜测，至少审稿人校对是否被 assign、forum_id、手动生成论坛帖子后检查论坛帖子的链接正常是可以用 python 脚本做得到的。至于是否已经在微信上编辑了这个就做不到了。

@Lchiffon CTO 请调研此方案。一个最大的问题就是类 netlift 之类的 check 是怎样实现的，是不是用 travis ci 之类的就可以。

**Comment by fyears** [comment]
另一个很拍脑袋的解决方案就是 https://developer.github.com/webhooks/

每次 pr 或者 commit 或者合适的动作发生时候，发送一个 post 到我们自己的某个服务器上（反正我们有一个放论坛的 vps 了），我们服务器上的某个脚本触发之后溜去论坛自动发帖，再自动回来 github 发个
 comment。2333。

类似于[这种](https://github.com/tensorflow/tensorflow/pull/13574)里面的 googlebot 和 tensoflow-jenkins “用户”

**Comment by Lchiffon** [comment]
我觉得如果搞自动化, 就搞的彻底点, 别再搞回来comment一下再找个人修改PR
把文章和论坛ID维护一个文件, 检查新文章没有ID就自动创建帖子,并修改文件, push到主分支中来....
@fyears 觉得如何

**Comment by fyears** [comment]
创建论坛post这一步，要看travis能否访问外网。

否则只能自建服务器了

**Comment by yihui** [comment]
我建议你们把这件事作为第二步去做，现在先不要考虑它（除非时间多得用不完）。当务之急是有个清单，论坛发帖只是清单里面的很小一步，就算忘了，对一篇文章的影响也是非常微弱的。另外我以前也说过，发帖这件事只是举手之劳，任何人都可以发， 不必把这个任务绑定在林枫身上；如果有一个清单，以后就不会忘，每次只不过是花二三十秒发个帖子而已。现在之所以落到这个地步，原因有二：一是没有一个流程；二是把这件事绑在一个人身上（鸡蛋放在一个篮子里）。只要这两个限制解除，我觉得对自动化的需求会大大降低。

**Comment by tcgriffith** [comment]
没想到随便回复一个帖子引发了一个issue, :sweat_smile: 我原本以为这步是自动化的说233

**Comment by yihui** [comment]
看，又来了：https://d.cosx.org/d/419228

**Comment by Perfectizer** [comment]
怪我。。。这段时间一直比较忙。。。没上github。。。错过了许多信息。。。之后我一定及时查看！！！！

**Comment by Perfectizer** [comment]
建议我们列个清单样，把待发布和已发布的文章注上各步骤有没有做到。@yihui

**Comment by Lchiffon** [comment]
https://github.com/cosname/cosx.org/pull/740 

我已经做了这个关于流程的PR，但好像没合并， 像[最新的PR里面](https://github.com/cosname/cosx.org/pull/746)就是严格按照这个流程做的...

**Comment by PuddingNnn** [comment]
这几个流程上我没建议了，建议加上一个哪个√谁负责来打，比如
主编安排审稿人（主编 副主编）
审稿、修改（审稿人）
文字编辑做校对工作 （审稿人）
论坛帖子负责人发帖并提供 forum_id 加入文章（林枫）
微信编辑（微信编辑）
合并 PR，发布文章（主编 副主编）
论坛帖子负责人更新帖子中的主站文章链接（林枫）

**Comment by yihui** [comment]
即使有打勾的选项，我看也几乎从来没有人按流程打勾。看看 https://d.cosx.org/u/COSeditor 里面有多少是“链接待发布”但永远忘记发布的。

上面我建议不要把这口锅绑在一个人身上，现在我具体一点：如果 @Perfectizer 忘记背锅，就请 @XiangyunHuang 背一下吧，因为你有论坛版主权限，可以修改帖子，把链接加上。

**Comment by yufree** [comment]
我补了下链接，有文章推送因为长时间无回应已经关了，有的则是还没有PR，还有的这个夏天陆续会发表出来，所以麻烦 @Perfectizer 清理下[这篇](https://d.cosx.org/d/420249--)与[这篇](https://d.cosx.org/d/420372-r)，其余待主站发表后请加入链接。

**Comment by XiangyunHuang** [comment]
@yihui 好的。最近的两篇还没有发出来，变分自动编码器这篇文章已经关闭了，另一篇我添加了链接

**Comment by Perfectizer** [comment]
@yufree 有的时间隔太久或者之前说要发现在还没发， 一直没有弄。我的锅== 我过两天完整检查一遍。自编码器那篇我把帖子删了，另外谢谢@XiangyunHuang

**Comment by Perfectizer** [comment]
@yihui 谢谢谢大提醒。因为之前有计划把老稿件都重整，所以提前开了不少帖。 个别帖是遗漏了@XiangyunHuang 已经补全，其他都还没发或者pr给关了。我们会尽快把该发的发出来～

**Comment by yihui** [comment]
谢谢林枫少侠！

**Comment by yihui** [comment]
还有，以后论坛帖子可否则合并 PR 的前一刻发（即：发完立刻合并），不要提前太长时间，否则一是容易引起误会，如 https://d.cosx.org/d/420750 二是如我上面所说，容易忘记更新帖子。

**Comment by LingrenKong** [comment]
考古一下，这个是不是已经自动化解决了？目前来看，COSeditor都是及时发了的，或许可以关掉这个issue了？

**Comment by yihui** [comment]
嗯，就是每次合并 PR 记得走完打勾的流程。
