### ISSUE TITLE
来开个Issue讨论下贴纸的事情

### ISSUE THREAD

**Issue by Lchiffon** [cosname/cosx.org#742]
![image](https://user-images.githubusercontent.com/7221728/32047309-1fe1a0e2-ba78-11e7-8283-263f0e1f44c8.png)

![image](https://user-images.githubusercontent.com/7221728/32047313-256f2822-ba78-11e7-9e99-c126c6745de6.png)

上海R会准备做两个贴纸, 一个是COS的, 一个是R的, 以后沙龙和R会也可以用, 大家看看有什么意见?

**Comment by Lchiffon** [comment]
有建议是用之前北京R会的这个设计, 但我也不清楚这个设计有没有版权...:
![image](https://user-images.githubusercontent.com/7221728/32047274-062fb2a6-ba78-11e7-91ad-04165fe29cda.png)

**Comment by feng-jings** [comment]
![r logo](https://user-images.githubusercontent.com/16065479/32077782-6f38d72e-ba59-11e7-9f75-ecf26c16fa37.png)

**Comment by feng-jings** [comment]
这个是第十届北京R会的主logo，有版权。R会网址是china-r.org

**Comment by feng-jings** [comment]
![cos logo](https://user-images.githubusercontent.com/16065479/32077858-ad889b5e-ba59-11e7-9d16-c35da900776e.png) 上面统计之都的Logo看着也有点糊，这里是比较大的清晰版

**Comment by Lchiffon** [comment]
![image](https://user-images.githubusercontent.com/7221728/32086370-3e80cd40-bb07-11e7-9f59-2a160cb35719.png)

第二版喽, 谢大大有提到边框有点肥, 不知道
@feng-jings 怎么看....

**Comment by yihui** [comment]
可能是我看我们自己的贴纸看习惯了：https://www.rstudio.com/products/rpackages/

**Comment by feng-jings** [comment]
谢大那个感觉比较美型lol..每个贴纸都有插画...我们这个就以logo做元素所以我认为宽度没什么问题？R会的边框饱和度会不会太低了感觉颜色过浅？另外网址不改成china-r.org吗？

**Comment by Lchiffon** [comment]
我没放china-r.org的原因是我觉得那个网站基本都没有更新, 图是去年的R会, 历史信息里面也有好多没更新的

**Comment by happyrabbit** [comment]
R会议的logo是不是可以加上年份，地点什么的。这样给人一种收集贴纸的冲动......

**Comment by fyears** [comment]
楼上的好主意……和 cosx 那条棱对称就好了

**Comment by Lchiffon** [comment]
诶呦, 我可以close这个了
