### ISSUE TITLE
404 NOT FOUND

### ISSUE THREAD

**Issue by Cloud2016** [cosname/cosx.org#744]
主站投稿按钮 <https://cosx.org/contribute/> 点击后报404错误

![cos](https://user-images.githubusercontent.com/12031874/32873257-fa03090c-cac5-11e7-903a-1b64acea5c09.JPG)

**Comment by yihui** [comment]
我点开没问题啊。其他人有问题吗？

**Comment by tomatoiscoding** [comment]
没问题

**Comment by fyears** [comment]
有问题。全部页面都 404。

是不是构建过程或者 cdn 有问题？？

**Comment by Cloud2016** [comment]
这下，投稿按钮没问题了，搜索按钮404了

**Comment by fyears** [comment]
20171117 再看，没问题了

**Comment by Cloud2016** [comment]
现在一切正常，我把 issues 关了
