### ISSUE TITLE
建议：文章流程列个清单

### ISSUE THREAD

**Issue by Perfectizer** [cosname/cosx.org#749]
建议像下面这样开个清单。。。执行完流程的人都勾选一下，这样大家看进度不需要一篇篇文章查看，只需要看这个清单就好。
![文章流程清单](https://user-images.githubusercontent.com/18381242/33986835-c5eb8cee-e0f9-11e7-8526-27748d16c75e.png)

@yihui @PuddingNnn @Lchiffon

**Comment by Lchiffon** [comment]
我觉得汇总的问题在于可能被忘掉这回事

做成PR模板能保证那个checklist没次都在PR里面出现， 这样就不会忘了

**Comment by fyears** [comment]
https://github.com/cosname/cosx.org/issues/739

这个 issue 其实可以关掉。

**Comment by yihui** [comment]
嗯，集中到 #739 讨论吧。
