### ISSUE TITLE
HTML 数字索引实体替换

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#77]
如 `&#8221;` 需要批量替换为 `–`

**Comment by yihui** [comment]
我又想了一下，其实冲突我们可以自己解决，不需要修订者操心。Github 现在很贴心地提供了网页界面解决冲突，很好用。

所以这个问题还是尽早咔嚓掉吧。

**Comment by yihui** [comment]
关于双引号的问题，可以先试试这个不太严谨的替换：

```r
gsub("”([^“”]+)”", "“\\1”", x)
```

提交个 PR 看看差异中的替换效果。

**Comment by hetong007** [comment]
有些一行里有多个引号对的就不行了，会出现下面的情况：

```
-依次选择菜单栏中的”File”, “New”,”R-Project”，打开新建R的工程的对话框。如下图所示
+依次选择菜单栏中的“File”, “New“,”R-Project”，打开新建R的工程的对话框。如下图所示
```

之前`New`前后是正确的，结果`New`后面的反引号被认为是和下一个反引号匹配，从而变成了引号…

**Comment by hetong007** [comment]
可以要求在两个反引号的检测时，要满足之前有零或若干对正反引号，然而我不会写这个正则…

**Comment by fyears** [comment]
不单纯用正则，用 python / r 逐个文件读进去，然后获取 match 的 list / vector，手动替换。。

现在我看到的效果全是右引号，好难受。。😥

**Comment by Lchiffon** [comment]
我还见到有这个: 
”取伪“ 
两个引号是反的

**Comment by fyears** [comment]
我 push 了一个，只 match 空格、中文、横线。肯定有漏，比如说有逗号、句号在中间的。这些情况正则也没办法了。

**Comment by yihui** [comment]
谢谢，批量处理能处理多少算多少吧，剩下的只能肉眼识别了。要是还有漏的就算了，追求完美的成本有点高。

**Comment by Lchiffon** [comment]
https://github.com/cosname/cosx.org/search?utf8=%E2%9C%93&q=%26%238221%3B&type=

已经搜不到了, 感觉可以关了
