### ISSUE TITLE
北京 R 会议宣传文章

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#8]
跪求用 Markdown 写……不然后面转 Markdown 又要经历一遍痛苦折磨 😭

**Comment by ksxinyuh** [comment]
好滴呀

**Comment by ksxinyuh** [comment]
https://github.com/ksxinyuh/chinar_2017_bj
主要内容大概是这样，之前说的tag和小尾巴有统一安排了嘛～有的话我加上
另外我应该在cos的下面建这个东西是吧...我先在自己的里面写的...不过没关系，都弄好了我再搬运过来

**Comment by yihui** [comment]
完美。标签可以加上，小尾巴不用加。谢谢！

**Comment by yihui** [comment]
PR #157 完成任务。
