### ISSUE TITLE
论坛公式组渲染问题

### ISSUE THREAD

**Issue by XiangyunHuang** [cosname/cosx.org#808]
如帖子所示 <https://d.cosx.org/d/420133-gitbook> 论坛里稍复杂的公式组是不是不受支持，又或者是我编辑公式的姿势不对？ 

$$
\begin{array}{rcll}
p(\boldsymbol{\theta}|Y) & = & \displaystyle \frac{p(\boldsymbol{\theta},Y)}{p(Y)}
& \text{ [条件概率定义]} \\
& = & \displaystyle \frac{p(Y|\boldsymbol{\theta}) p(\boldsymbol{\theta})}{p(Y)}
& \text{ [链式法则]} \\
& = & \displaystyle \frac{p(Y|\boldsymbol{\theta})p(\boldsymbol{\theta})}{\int{\Theta}p(Y,\boldsymbol{\theta})d\boldsymbol{\theta}}
& \text{ [全概率公式]} \\
& = & \displaystyle \frac{p(Y|\boldsymbol{\theta})p(\boldsymbol{\theta})}{\int{\Theta}p(Y|\boldsymbol{\theta})p(\boldsymbol{\theta})d\boldsymbol{\theta}}
& \text{ [链式法则]} \\
& \propto & \displaystyle p(Y|\boldsymbol{\theta})p(\boldsymbol{\theta})
& \text{ [$Y$ 是固定的]}
\end{array}
$$

**Comment by XiangyunHuang** [comment]
现在 Github 越来越强了，公式也支持直接渲染了。

**Comment by yufree** [comment]
目前优先轻量级加载
