### ISSUE TITLE
关于主站文章中文标点符号和表格标题字体的问题

### ISSUE THREAD

**Issue by Perfectizer** [cosname/cosx.org#835]
#### 这两个问题应该主要跟CSS有关。

> 1. 处理中文时可能存在文末标点符号独占一行的问题
> 2. 表格：row和column的head字体会出现不一致的情况，可能需要调整一下

@Lchiffon

**Comment by yihui** [comment]
句号的问题应该是数学公式与句号之间有空格导致的。如果去掉空格的话，数学公式会粘在句号上移到下一行。因为中文是不可压缩、不可从中折断的方块字，这个断行问题是个极难解决的问题：https://yihui.name/cn/2017/04/space/ 目前没有解决方案，也几乎不太可能有解决方案；要么一坨公式粘着句号一起挪到下一行，要么句号粘在公式后面超出页宽，两个方案都丑。

![image](https://user-images.githubusercontent.com/163582/58893228-5385f000-86b5-11e9-99c8-b7b123efc469.png)

表格的表头字体加粗了，这个表格是特殊情况，它是个列联表，所以第一行并不是表头；为了排版一致性，建议把第一列也加粗好了。

![image](https://user-images.githubusercontent.com/163582/58893656-2dad1b00-86b6-11e9-9654-3c418d4a1532.png)

**Comment by yufree** [comment]
第一个坑太深就随缘了。第二个我手动加粗的，因为可能存在没有第一列表头的情况，统一改掉可能会有其他影响，不过没想到 Blackfriday 不支持表内星号加粗，所以就用 html 标签了。

**Comment by yihui** [comment]
中。
