### ISSUE TITLE
主站 MathJax 特别慢

### ISSUE THREAD

**Issue by yixuan** [cosname/cosx.org#838]
在美国访问主站公式渲染极其慢，不知道有没有更好的选择？

**Comment by yihui** [comment]
那还是换 CloudFlare 那边的 CDN 资源吧。换过来看国内访问速度如何。

**Comment by yixuan** [comment]
突然又快了起来，真是玄学……先关了，问题重现的时候再开。

**Comment by yihui** [comment]
我感觉 BootCDN 偶尔就是会抽风，大概是每年三四次的频率。
