### ISSUE TITLE
考虑转回 github 自己的 CI 来 build 网站

### ISSUE THREAD

**Issue by fyears** [cosname/cosx.org#859]
github 提出了自己的 ci：https://github.com/features/actions

已经找 @Lchiffon 去申请 beta 名单。如果成了的话，可以考虑择日迁回来，去除 netlify 的依赖。

好处是我们可以增加一些中间状态，如 rmd 转换、语法检查等。

**Comment by tcgriffith** [comment]
build 之后主站是用gh page做部署吗？

**Comment by fyears** [comment]
如果采取这个方案，那么是的，使用 gh-pages

**Comment by tcgriffith** [comment]
个人经验是gh-page对于国内访问速度要优于netlify，国外倒是大差不差

**Comment by XiangyunHuang** [comment]
启用 Action 还能支持 PR 预览吗？当时采纳 Netlify 好像是挺看重这个特性的

**Comment by XiangyunHuang** [comment]
为什么部署的站点完全错乱了 https://xiangyunhuang.github.io/cosx.org/

**Comment by tcgriffith** [comment]
> 为什么部署的站点完全错乱了 https://xiangyunhuang.github.io/cosx.org/

chrome开发者模式里慢慢找吧

看了一眼应该是baseurl设置问题，css和js什么的都404了

**Comment by XiangyunHuang** [comment]
还是让大神们来操作吧

**Comment by yufree** [comment]
考虑到rmd文档的编译重现性问题，暂时不考虑GHA方案。
