### ISSUE TITLE
建议: 用fuse.js替代algolia

### ISSUE THREAD

**Issue by tcgriffith** [cosname/cosx.org#877]
今天在自己的站试了一下fuse.js,完全没问题。

优势是去掉algolia依赖，把搜索放到客户端浏览器来做，这样就不用每周跑个cronjob把索引推到algolia服务器了

实现起来也简单，加个js加几行css，索引的话打开hugo自带但是默认关闭的index.json即可，而额外的js跟css也可以只在搜索页一个页面上加载，对目前网站速度可以说没有影响。

链接：
https://gist.github.com/eddiewebb/735feb48f50f0ddd65ae5606a1cb41ae

**Comment by fyears** [comment]
怎么看这玩意都是把所有文章内容塞到一个大 json 里啊。。看起来不是很靠谱。。。

**Comment by tcgriffith** [comment]
试了一下，所有文章加起来的json索引5.1MB。

感觉相当于用户第一次搜索就得下一张大图。

**Comment by yihui** [comment]
我今天研究搜索的时候也看了一下 fuse.js，感觉还不错啊。5Mb 的文件确实有点大，但要是服务器端支持 gzip 传输的话，也就没多大了。
