### ISSUE TITLE
论坛无法访问

### ISSUE THREAD

**Issue by nanxstats** [cosname/cosx.org#878]
看起来好像是数据库连接问题。

```
Flarum encountered a boot error (Doctrine\DBAL\Driver\PDOException)
SQLSTATE[HY000] [2002] No such file or directory
thrown in /var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 31
```

<img width="1018" alt="Screen Shot 2020-01-27 at 7 06 29 PM" src="https://user-images.githubusercontent.com/199363/73224772-927f1f00-4138-11ea-9e28-a74586d142ca.png">

**Comment by yihui** [comment]
最近好像挂得很频繁啊 @yixuan

**Comment by yixuan** [comment]
从服务器后台来看，感觉像是机器人自动注册或者恶意攻击，导致数据库挂掉。这玩意没法防啊……

![Screenshot_2020-01-28 linode1943777 - Summary Linode Manager](https://user-images.githubusercontent.com/216398/73265168-64cec000-41a2-11ea-9351-4fa1e2e08d08.png)

**Comment by nanxstats** [comment]
结合截图和最近挂得频繁判断，这像是得罪了某位大爷，被 DDOS 了 …… 😂 

防护还是有办法的：在裸的 Linode 前边套一层 Cloudflare，这样进来的流量都会先被 CF 清洗一遍。后边节点用的 IP 得换一个，因为之前真实的 IP 已经暴露了。

[基本的设置](https://www.linode.com/docs/networking/dns/how-to-set-up-cloudflare-with-linode/)、[更严密的设置](https://www.digitalocean.com/community/tutorials/how-to-host-a-website-using-cloudflare-and-nginx-on-ubuntu-16-04)。

国内的访问需要测一下，理论上没有问题，在国内 CF 是和某云服务商合作的。

**Comment by nanxstats** [comment]
最近感觉访问稳定了一些，先在此结帖了。
