### ISSUE TITLE
properly display numbered list with paragraph

### ISSUE THREAD

**Issue by szcf-weiya** [cosname/cosx.org#879]
在 [十字路口的统计学: 谁在应对挑战？（一）](https://cosx.org/2020/01/crossroad-statistics-who-meet-challenge-1/) 中，1.2 节上面的 numbered list 没有正常显示，应当为 1,2,3 点，而下图中为 1,1,1
![image](https://user-images.githubusercontent.com/13688320/73273002-40b0c480-421e-11ea-839d-5f4b2fb94bb8.png)
但是在 markdown 中测试（比如 GitHub 的 preview）或者 rmarkdown （knit to html）中尝试，都能正常显示 numbered list；另外我在 Jekyll + kramdown 环境中试过，却也不能正常展示，但如果我在每一段前面（如第一段“由于改进的”）加上一个 tab space 就能正常显示了。所以不知道 tab space 是否能够解决这个问题？或者有其他方法？

**Comment by yufree** [comment]
因为列表间分段了，所以重新开始计数，缩进后则不被认为分段，可以参考[这里](https://pandoc.org/MANUAL.html#pandocs-markdown)。稍后我会用缩进方法修复，感谢报告！
