### ISSUE TITLE
栏目分类有重项

### ISSUE THREAD

**Issue by XiangyunHuang** [cosname/cosx.org#888]
https://cosx.org/categories/ 下 【R 语言】栏目有两项，不知是什么原因？

**Comment by yufree** [comment]
链接上看一个R后面有空格，一个没有，虽然看起来都有。

**Comment by XiangyunHuang** [comment]
点栏目分类的第一个 R 语言跳转到 https://cosx.org/archives/  而不是 https://cosx.org/categories/R%e8%af%ad%e8%a8%80

**Comment by yihui** [comment]
已运行 `blogdown:::find_categories('R 语言', open = TRUE)` 修正。

**Comment by XiangyunHuang** [comment]
藏得有点深啊，很实用的小功能

**Comment by yihui** [comment]
就像我以前说过的，写代码容易，只是后续事情麻烦，包括写文档、宣传、维护。好多代码我知道对别人有用，但实在懒得导出这些函数，就藏在各个角落，然后过一阵子我自己也忘记了。
