### ISSUE TITLE
论坛注册邮件无法发送至 outlook.com ？

### ISSUE THREAD

**Issue by boltomli** [cosname/cosx.org#889]
注册以后一直无法验证，再次发送貌似也没有效果。

**Comment by boltomli** [comment]
不喊就到不了……喊了就到了

**Comment by boltomli** [comment]
This confirmation link has already been used or is invalid.

但是发送的链接不能用

**Comment by boltomli** [comment]
虽然显示无效，实际上好像生效了？等我再观察观察……

**Comment by yihui** [comment]
境外输入的电子邮件也要隔离 14 天？

**Comment by yixuan** [comment]
这故事真够曲折的……以及确认一下链接是不是包含了句号之类的字符，手动调整下应该就行了。
