### ISSUE TITLE
论坛400错误

### ISSUE THREAD

**Issue by tcgriffith** [cosname/cosx.org#891]
服务器返回400错误，手机端跟电脑端都显示错误。症状为无法回帖，无法退出登录，但是

-F12显示以下错误
```
Failed to load resource: the server responded with a status of 404 ()
/api/discussions/420363:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
/api/posts:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
/api/discussions/420363:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
/api/discussions/421108:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
/api/discussions/421375:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
```

直接浏览器访问这些api的接口都可以访问。

**Comment by yixuan** [comment]
应该已经好了，有时候服务器会出现莫名奇妙的问题，多半是被恶意攻击。

**Comment by yihui** [comment]
我最近也碰到过好几次无法审核帖子的情况，且无法退出登录。每次点审核帖子，页面上都出来个错误框，而且已读的帖子无法标记已读。后来我后台清理了一下论坛缓存就好了，但这个操作是在 @tcgriffith 报告之前做的（前两天）。感觉最近论坛有什么幺蛾子。

**Comment by yihui** [comment]
又开始了，任何操作都会出现一个错误提示：

![image](https://user-images.githubusercontent.com/163582/79055017-4c057080-7c0f-11ea-8ddf-36d5fcb3a011.png)

**Comment by yixuan** [comment]
不是巧合，之前服务器报告CPU使用连续两小时超过90%，不知道又是被什么人攻击了。你说我们就这么小个破站怎么还有人盯上呢……😰

**Comment by tcgriffith** [comment]
查系统日志啊

**Comment by yihui** [comment]
我现在启用了 Cloudflare 的代理模式，这两天看看 Cloudflare 能否挡住一些攻击。但因为我们之前没有使用代理模式，所以服务器 IP 已经暴露；如果攻击者是利用 IP 攻击的话，那这个代理也没用了。

**Comment by yixuan** [comment]
破案了，是 cron 任务被攻击用来挖矿了，所以 CPU 会出现占满的情况。目前暂时修复了问题，但如果攻击手段升级了可能就得换个 IP 了。

**Comment by yanlinlin82** [comment]
挖矿。。。难道远程登录权限被获取了？

**Comment by tcgriffith** [comment]
话说服务器是实体服务器还是租用的虚拟机啊…

**Comment by yixuan** [comment]
虚拟的，类似的问题有人也遇到过：https://askubuntu.com/questions/1161003/strange-cron-job-takes-up-100-of-cpu-ubuntu-18-lts-server。
