### ISSUE TITLE
R Markdown 制作幻灯片模版

### ISSUE THREAD

**Issue by XiangyunHuang** [cosname/cosx.org#901]
先立个字据 https://d.cosx.org/d/421591-beamer/11

**Comment by XiangyunHuang** [comment]
属于 https://github.com/cosname/cosx.org/pull/914 @llijiajun

**Comment by XiangyunHuang** [comment]
自己挖的坑自己先填了 https://xiangyun.rbind.io/2021/05/beamer-down/

**Comment by yufree** [comment]
可以投主站啊

**Comment by XiangyunHuang** [comment]
投主站的话，还有点单薄，等我以后充实下再投吧！
