### ISSUE TITLE
统计月读（2020年9月）

### ISSUE THREAD

**Issue by XiangyunHuang** [cosname/cosx.org#906]
请回复 issue 进行文章推荐与招聘投稿，内容须与统计/数据科学相关，是否采纳取决于编辑部意见。

文章推荐包括学术论文、博客、书籍、教程或软件等的推荐，如果是英文文章在月报发布后自动作为翻译备选文章。

招聘主要面向学术界与工业界的招聘信息发布且岗位要与统计/数据科学相关。

文章推荐格式如下：

推荐语：（几句话就可以，可长可短，有态度不严肃）

推荐人：（建议用真名）

链接：（论文建议给doi，其余给链接）

招聘信息格式如下：

岗位介绍：（例如博士生、博后、xx公司软件工程师等）

工作地点：（具体到城市）

联系方式：（网站链接或邮箱）

**Comment by boltomli** [comment]
* 推荐语：关于 R 语言教学，作者针对学生是编程初学者的情况提出了 Tidy 存在的多种问题。
* 推荐人：Song Li
* 链接
  * [译文](https://github.com/boltomli/TidyverseSkeptic) 已获得作者同意
  * [原文](https://github.com/matloff/TidyverseSkeptic)

**Comment by XiangyunHuang** [comment]
@boltomli  是否有兴趣整理下发到统计之都主站？

**Comment by yufree** [comment]
推荐语：上次推荐的 stackgbm 包是用来解决模型叠加问题的，单一模型总有预测性能的天花板，多模型整合后则可实现更好的预测效果，毕竟只有小孩子才做选择。这是肖楠版主在一次研讨会上对这个包相关案例的介绍，非常有启发性，3小时7分30秒开始。

推荐人：于淼

链接：https://georgetown.zoom.us/rec/play/RKrAQtFEbH1C-KX2j1_xR0UB8_tXLYzn7p7GDVMo2FXEzw2T9ZIgLr3Yb18UKiOmGKyc7_entLS1b6OP.pxJ4W_bi9Rik8DyV

**Comment by boltomli** [comment]
> @boltomli 是否有兴趣整理下发到统计之都主站？

可以的，需要一些时间看看文档怎么处理 :)

**Comment by yufree** [comment]
推荐语：可视化发展还是很快的，有时候还没搞明白一种方法这个方法就被更好的替代了。在降维可视化上，t-SNE还没等普及到教科书里，同样基于流形分析的UMAP就跑出来宣告全面压制了。作为用户，UMAP最直观感受就是不会出现 t-SNE 那种重复性不好的情况，而且速度快了很多。

推荐人：于淼

链接：https://towardsdatascience.com/how-exactly-umap-works-13e3040e1668

**Comment by yufree** [comment]
推荐语：斯坦福大学 Stats366/Bios221 的配套在线电子书，主要内容是基于R语言的现代生物统计方法，案例很丰富，讲解深入浅出，适合生物统计入门。

推荐人：于淼

链接：https://www.huber.embl.de/msmb/

**Comment by yufree** [comment]
推荐语：医疗诊断算法由于传统习惯考虑了种族，结果会导致黑人得到肾移植的机会低于白人，这种算法习惯会放大歧视问题且很难被察觉，《连线》也对此进行了[报道](https://www.wired.com/story/how-algorithm-blocked-kidney-transplants-black-patients/)，机器学习算法设计时预测变量选择不能单纯照搬经验，要更多考虑背景原理来选择更底层的独立变量。

推荐人：于淼

链接：https://link.springer.com/article/10.1007/s11606-020-06280-5

**Comment by yufree** [comment]
推荐语：今年是 Github Actions 大规模取代 Travis 的一年，这篇文章给出了容器技术在 R 包调试上的作用，如果你还没着手学习持续集成技术，现在应该是个好时机。

推荐人：于淼

链接：https://kbroman.org/blog/2020/12/03/debugging-with-docker-and-r-devel/

**Comment by yufree** [comment]
推荐语：统计月读2019年第一期我们推荐了 Radix 包，目前已经改名为 distill，如果说 rticles 包是对当前期刊的一种妥协，输出仍然是 tex 文档，那么新版 distill 包可以看做是完全基于网页输出的学术期刊的技术基础，直出静态网页且支持文献引用，非常适合学术人员快速分享自己的一页纸式的研究成果。

推荐人：于淼

链接：https://blog.rstudio.com/2020/12/07/distill/

**Comment by yufree** [comment]
推荐语：flowingdata 选出的年度可视化项目，疫情可以说占了大部分主题。

推荐人：于淼

链接：https://flowingdata.com/2020/12/23/best-data-visualization-projects-of-2020/

**Comment by yufree** [comment]
推荐语：Gelman 总结的过去50年中最重要的统计思想，包括 counterfactual causal inference, bootstrapping and simulation-based inference, overparameterized models and regularization, multilevel models, generic computation algorithms, adaptive decision analysis, robust inference, and exploratory data analysis.

推荐人：于淼

链接：https://arxiv.org/abs/2012.00174

**Comment by yufree** [comment]
推荐语：PLS-DA 可以说是最简单的机器学习模型了，但如何用好用对也是需要了解原理的，这篇名为“So you think you can PLS-DA?” 用真实数据研究了该方法与 PCA 的比对并解释了优缺点，适合实验学科人员阅读。

推荐人：于淼

链接：https://www.biorxiv.org/content/10.1101/207225v3

**Comment by yufree** [comment]
推荐语：这是一本向 R 用户介绍 javascript 的电子书，适合 R 用户特别是 shiny 用户阅读。

推荐人：于淼

链接：https://book.javascript-for-r.com/
