### ISSUE TITLE
R Markdown 格式的稿件如何处理

### ISSUE THREAD

**Issue by ShichenXie** [cosname/cosx.org#913]
目前还是无法预览，这里是否需要修改下？`index.zh.html` 这个文件应该是不存在的，对应的 `index.zh_files/anchor-sections/anchor-sections.css` 文件是没有的，包括下一行的js，可否直接删了这两行？

_Originally posted by @yufree in https://github.com/cosname/cosx.org/pull/912#discussion_r523788126_

已经修改了。不是很熟悉这个啊。不都是blogdown生成的么，最近不是可以支持rmd了么

**Comment by XiangyunHuang** [comment]
关于 Rmd 格式稿件怎么弄，我大胆 CUE 一下谢大 @yihui 看目前的正确姿势是什么？

**Comment by yihui** [comment]
回复：https://d.cosx.org/d/421573/158

Rmd 稿件其实很简单，通过 `blogdown::serve_site()` 预览生成的所有文件都传上来就好了。这事情之所以看起来复杂，只是因为一个强迫症问题：我不太倾向于把 Rmd 文档生成的副产品（如图片）传到这个库里，因为这样很容易让库的体积膨胀到很大。你在论坛帖子里问的问题核心就是这些图片有没有办法自动上传到什么图床。技术上这当然是可以做到的。比如给 R 图片设置个钩子函数自动上传，knitr 里有 `knitr::imgur_upload()`，但 Imgur 是被墙的。

所以说来说去，还是不如就通过 GIT 把所有副产品都提交上来算了；技术上这样最简单。

**Comment by LingrenKong** [comment]
> 关于 Rmd 格式稿件怎么弄，我大胆 CUE 一下谢大 @yihui 看目前的正确姿势是什么？

如果rmd文件是单独一篇文件（比如之前是用rmd做的演讲slide，现在来投稿），或许可以直接让作者自行更改knitr参数导出？弄成md文件就解决了大部分问题，只有图片需要加链接上传。

```
output: 
  md_document:
    variant: gfm
```

**Comment by yihui** [comment]
演讲稿和文章的区别还是挺大的，改一下 `output` 格式可能还远远不够。实际上也不需要改，任何 Rmd 文档丢到 blogdown 网站里就会自动变成网页，不需要做任何修改。

**Comment by XiangyunHuang** [comment]
目前为止，关于 R Markdown 稿件，PR  https://github.com/cosname/cosx.org/pull/1004 的方式应该是最佳的。

**Comment by XiangyunHuang** [comment]
一些补充评论：关于博客文章采用 Rmd 投稿带来的副作用---代码仓库增大，我之前在自己的个人博客里都是截图，虽避免了引入 JS 库，却没了交互和动态特性。将 JS 库放在全局位置复用可能带来版本不兼容，我之前在一篇文章里同时用 Python 版 plotly 和 R 版 plotly 都会冲突， echarts4r/leaflet 这些应该也会出现类似的问题。后来，在稳定性面前，我决定接受仓库增大的副作用，即使再增加10篇这样的文章，也不过是又增加100M。文章一旦发出，就再也不想为之操心。
