### ISSUE TITLE
注册出错：糟糕，出错啦！请刷新页面重试

### ISSUE THREAD

**Issue by CyrusYip** [cosname/cosx.org#915]
# 我的尝试

1. 用户名用了 `Cyrus Yip` 和 `CyrusYip`
2. 用的是 hotmail 邮箱（截图时把地址改成了`xxxxx.xxxx`）
3. 密码用了 `字母+数字` 和 `字母+数字+特殊符号`

结果都无法注册。

![image](https://user-images.githubusercontent.com/60951091/100861121-58a34580-34cc-11eb-9d02-c5f48bd19b82.png)

请问是网站出了问题还是我操作有误呢？

**Comment by yixuan** [comment]
稍等，我来检查下。

**Comment by yixuan** [comment]
搞定了，是因为一个第三方插件太老了，刚才已经更新，麻烦再试一下。

**Comment by CyrusYip** [comment]
谢谢你， @yixuan。我可以注册了，但是收不到验证邮件，真奇怪。我点了好几次重新发送验证邮件，也不行。收件箱和垃圾邮件都没有，是不是发送邮件的服务也有问题呢？

**Comment by yixuan** [comment]
我用Gmail试了下是可以收到的，估计是hotmail的内部规则拦截了。刚才已经帮你手动激活了。

**Comment by CyrusYip** [comment]
十分感谢，邮箱认证好了。那我需要重置密码或者通过邮箱接收论坛信息的话，是不是还会收不到邮件？直接把论坛的邮箱添加到白名单能解决这个问题吗？

**Comment by CyrusYip** [comment]
晚上 9 点多注册好，晚上 10 点多按了重置密码，终于在早上 1:18 收到了验证邮件，1:19 收到了重置密码邮件，邮件都在垃圾邮件里，不过总算是可以了。中间隔了好久啊，把两份邮件移出了垃圾邮件，希望下次能准时收到。
