### ISSUE TITLE
文章推荐

### ISSUE THREAD

**Issue by Li705772676** [cosname/cosx.org#923]
这是Karim Douieb用R写的一份著名可视化作品 «Land doesn't vote, people do» ，展示了公众投票的结果。在此过程中使用的所有数据都是通过瑞士开放政府数据平台opendata.swiss检索的，使用的数据代码可以在链接内找到。

推荐人：李璇

链接：https://github.com/zumbov2/votemapswitzerland

**Comment by yufree** [comment]
收到！已经转到一月月读 #922 ，以后我们会在月底前三天开放下月投稿，这样方便整理发微信或主站。
