### ISSUE TITLE
统计月读（2021年2月）

### ISSUE THREAD

**Issue by yufree** [cosname/cosx.org#924]
请回复 issue 进行文章推荐与招聘投稿，内容须与统计/数据科学相关，是否采纳取决于编辑部意见。

文章推荐包括学术论文、博客、书籍、教程或软件等的推荐，如果是英文文章在月报发布后自动作为翻译备选文章。

招聘主要面向学术界与工业界的招聘信息发布且岗位要与统计/数据科学相关。

文章推荐格式如下：

推荐语：（几句话就可以，可长可短，有态度不严肃）

推荐人：（建议用真名）

链接：（论文建议给doi，其余给链接）

招聘信息格式如下：

岗位介绍：（例如博士生、博后、xx公司软件工程师等）

工作地点：（具体到城市）

联系方式：（网站链接或邮箱）

**Comment by YueeXiang** [comment]
推荐语：与客服对话“遭遇”聊天机器人的体验很神奇，但聊天机器人背后的机制并不复杂——在R中短短一段代码就可以完成文本匹配，就可以和聊天机器人对话啦。此外，R代码简单易懂，也便于对语言模型进行修改和扩展。
推荐人：向悦
链接：https://blog.ephorie.de/eliza-chatbot-in-r-build-yourself-a-shrink

**Comment by yanlinlin82** [comment]
推荐语：法国新冠检测数据的日历热图形式展示，能非常直观地看出与周为单位呈现的周期性规律。
推荐人：颜林林
链接：https://guillaumepressiat.github.io/blog/2021/01/covidview-si-dep-echarts4r

**Comment by yufree** [comment]
推荐语：rstudio::global 2021 的报告视频列表，关注R生产力环境的朋友可以找到一些新项目或案例来模仿学习。

推荐人：于淼

链接：https://rstudio.com/resources/rstudioglobal-2021/

**Comment by Ryanna-github** [comment]
推荐语：R 中的数据结构列表（List）可以成为 R Markdown 报告行内数据展现的利器，避免了变量名过长冗余，整个报告信息结构井井有条。除此之外，作者还介绍如何用 `tidy()` 整理模型信息等其他小技巧。

推荐人：任焱

链接：https://www.tjmahr.com/lists-knitr-secret-weapon/

**Comment by dddd1007** [comment]
推荐语：在不确定环境当中的最优决策过程是如今计算认知科学, 自动化控制以及机器学习的重要研究对象. 斯坦福大学的三位教授梳理了这一领域的基本概念与知识, 对其中的公式进行了深入浅出的讲解, 并给出代码实现.

推荐人：夏骁凯

链接：https://algorithmsbook.com

**Comment by rucwyf** [comment]
推荐语：相信有很多人会用Rmarkdown，但不会自己写包，fusen包可以帮助大家通过Rmarkdown写R包，以此来节省大量的时间。

推荐人：王祎帆

链接：https://rtask.thinkr.fr/fusen-create-a-package-from-a-single-rmarkdown-file/

**Comment by yufree** [comment]
推荐语：哥大的这个开放教材项目收集了七百万份英文教纲中的参考书目教材并可视化成了知识图谱，可以看全学科的概况及哪些书被课程引用的最多，适合作为探索新领域的指南，资料数排前三的学科是商科、教育跟文学，这个巨大的网络大概就是人类教育的主动脉了，不过仅限于英文，因为其中文下排第一的书是《中文听说读写》。

推荐人：于淼

链接：https://galaxy.opensyllabus.org/

**Comment by yufree** [comment]
推荐语：主成分分析可能是做常用的多元统计分析方法了，这篇文章把主成分分析用到了图像异常区域检测上可以辅助理解主成分分析过程，另外是不是美颜相机也可以用类似的原理来磨皮祛斑。

推荐人：于淼

链接：https://rpubs.com/sandipan/191774

**Comment by MelodyRen1998** [comment]
推荐语：如何使用Pandoc的自定义过滤器来修改你的源文档？作者以Bookdown/Rmarkdown中创建书为例，解释了过滤器如何与Pandoc一起工作，并介绍了如何编写自己的过滤器。

推荐人：任怡萌

链接：https://jmablog.com/post/pandoc-filters/

**Comment by Li705772676** [comment]
推荐语：这篇文章分享了如何帮助你的R包在使用它的论文里被列为参考资料。同时，它还提到了一些使用者可能面临的障碍，并解释了如何跟踪软件包的使用情况。

推荐人：李璇

链接：https://ropensci.org/blog/2021/02/16/package-citation/

**Comment by jueyun** [comment]
推荐语：这篇文章介绍了新发布的 tiktokrmd包，它可以把tiktok视频嵌入RMD文件中。文章提供了tiktokrmd包的下载方式以及使用教程，通过这个包，用户可以非常方便的把tiktok视频展示在RMD文件中。

推荐人：操懿

链接：https://www.littlemissdata.com/blog/tiktokrmd

**Comment by JinhuaSu** [comment]
推荐语：厌倦了git代码协作，想要像在线文档一样激情四射地同时编程，面向对象编程不如成双成对编程，叫上你的儿子或者爸爸一起快乐开黑。服务器上配置R，搭配vscode的实时代码编辑插件，以及开黑语音插件。

推荐人：苏锦华

连接：https://ivelasq.rbind.io/blog/vscode-live-share/

**Comment by JinhuaSu** [comment]
推荐语：借这篇文章安利两个包，无情的抢课按键精灵chromote，yihui的写轮眼pdf。文章作者基于写轮眼开发了加入交互元素的XaringanExtra包，打印pdf时交回元素无法很好打印，使用chromote逐页打印再合并解决了该问题--xaringan2pdf包。

推荐人：苏锦华

连接：https://www.garrickadenbuie.com/blog/print-xaringan-chromote/
