### ISSUE TITLE
去掉链接中的域名部分

### ISSUE THREAD

**Issue by yihui** [cosname/cosx.org#96]
例如 `https://cos.name/2008/12/p-value/` 可以批量替换为 `/2008/12/p-value/`。这样网页就不会受限于特定域名，搬到任何域名下都可用（包括本地 127.0.0.1 预览）。

**Comment by fyears** [comment]
故技重施。。。😛

```regex
https{0,1}:\/\/cos.name\/\d{4}\/\d{2}\/
```

**Comment by yihui** [comment]
上！

**Comment by fyears** [comment]
只修改了链接向 post 的。其余的比如说 upload 的，不是 `/2008/10/...` 的，都不修改。

**Comment by yihui** [comment]
这是对的

**Comment by fyears** [comment]
不得不说，批量修改很有爽感。。不过这种事很难多干。。
