### ISSUE TITLE
左引号显示为右引号

### ISSUE THREAD

**Issue by szcf-weiya** [cosname/cosx.org#965]
https://cosx.org/2021/08/study-on-statistics-overseas-students-before-1949/
如下，左引号显示为右引号

![image](https://user-images.githubusercontent.com/13688320/131082725-15536f90-f8c2-4b81-a2fd-469405f151bd.png)

不过也有正常的，

![image](https://user-images.githubusercontent.com/13688320/131082781-f3188ea7-b34c-43a1-ab69-bb48763edf95.png)

但原文似乎都是英文引号 `"`，并非 typo。

**Comment by XiangyunHuang** [comment]
火眼精金，点赞👍

**Comment by yihui** [comment]
编辑部有谁来修一下咩，不然火眼金睛的眼力都浪费了。

**Comment by szcf-weiya** [comment]
其实我更好奇为什么既然都是成对英文引号，为什么有的地方能够正确渲染，而有的地方却失败了。是否是某处底层渲染机制，比如 Markdown -> HTML 没有正确处理？所以想提出来看看，能不能从根本上解决问题。

当然直接改成中文引号或许更直接。

**Comment by yihui** [comment]
我猜应该是渲染引擎（Hugo）的问题。据我的经验，Markdown 渲染引擎对中文支持不是很好，一般应该是只有标点符号处以及句首句末的直引号能被正确渲染为弯引号。

**Comment by szcf-weiya** [comment]
噢噢，如果是这样，那目前就直接像 https://github.com/cosname/cosx.org/commit/7f3206dae982170eae608fdbb86485a1429a4125 那样改成中文引号？

**Comment by yihui** [comment]
嗯，我觉得直接用中文引号就好了。
