### ISSUE TITLE
增加对 Google 版思源宋体（Noto Serif CJK SC）支持

### ISSUE THREAD

**Issue by chuxinyuan** [cosname/cosx.org#974]
## 问题描述

Ubuntu 系统上使用的是 Google 版思源宋体，而不是 Adobe 版的，名称有差异，导致 Ubuntu 系统下思源字体不能正常渲染，目前我的 Ubuntu 20.04 LTS 安装了微软雅黑，所以目前我的电脑上显示的是微软雅黑字体。

## 解决方案

目前我已向 [hugo-xmag](https://github.com/yihui/hugo-xmag) 主题提交了 [Pull requests](https://github.com/yihui/hugo-xmag/commit/dca58a1150c5c89e5ecc48720321ef1ea225aaf7) 解决了此问题，其实就是 fonts.css 文件里增加 'Noto Serif
CJK SC' 字体。

## 关于统计之都主站字体问题

统计之都主站主题引用的是 hugo-xmag 四年前的[一个分支](https://github.com/yihui/hugo-xmag/tree/412c0591715610b9ce78509a127de31526d83764)，并在此基础上做了定制，我不知道如何对这个分支提交 PR。因此，需要劳驾官人帮忙修改。

**Comment by yihui** [comment]
https://github.com/cosname/cosx.org/blob/373ecd4ecdc9b4f2c53927a303e4bddfeededcd2/static/css/fonts.css#L2
