### ISSUE TITLE
an invalid image url

### ISSUE THREAD

**Issue by szcf-weiya** [cosname/cosx.org#992]
here is an invalid image,
![image](https://user-images.githubusercontent.com/13688320/142460220-269a57ef-f8f9-4f08-b076-e203b3e8d14e.png)

the content source is https://github.com/cosname/cosx.org/issues/934

> 推荐语：只需要给Pycharm安装一个R插件，就可以在Pycharm中运行R代码。激活R插件后，重新启动Pycharm就可以在PyCharm R控制台中编写R脚本文件，从而无需在不同的IDE之间进行切换，提高工作效率。
> 
> ![R code in Pycharm plugin](https://camo.githubusercontent.com/513ed60b72ec3f3eb17d06bc5eea286d2681b43616ad8f03cbd61bc9e23ec1f9/68747470733a2f2f66696e6e73746174732e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032312f30342f522d636f64652d696e2d7079636861726d2d706c7567696e2e706e67)
> 
> 推荐人：任怡萌
> 
> 链接：https://finnstats.com/index.php/2021/04/05/how-to-run-r-code-in-pycharm/

where the url 

```
![R code in Pycharm plugin](https://camo.githubusercontent.com/513ed60b72ec3f3eb17d06bc5eea286d2681b43616ad8f03cbd61bc9e23ec1f9/68747470733a2f2f66696e6e73746174732e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032312f30342f522d636f64652d696e2d7079636861726d2d706c7567696e2e706e67)
```

is invalid.

**Comment by XiangyunHuang** [comment]
<img width="1151" alt="截屏2021-11-19 上午11 09 42" src="https://user-images.githubusercontent.com/12031874/142558474-dcacade7-af75-48dd-93d7-d41ae8529428.png">

我这边能正常展示，应该不是无效，可能是 @szcf-weiya 那边网不好。

另外，每篇文章的图，我们最好都有备份，并将链接替换为我们自己的图床生成的，这个事怡轩 @yixuan 在弄，不知道进行得怎么样了

**Comment by yihui** [comment]
这幅图我在 Chrome 和 Firefox 里都看不了。图片地址似乎是无效的图片：https://camo.githubusercontent.com/513ed60b72ec3f3eb17d06bc5eea286d2681b43616ad8f03cbd61bc9e23ec1f9/68747470733a2f2f66696e6e73746174732e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032312f30342f522d636f64652d696e2d7079636861726d2d706c7567696e2e706e67 原作者似乎也删掉了原图：https://finnstats.com/wp-content/uploads/2021/04/R-code-in-pycharm-plugin.png

你要是能看见图，就重新传一份替换掉吧。

**Comment by XiangyunHuang** [comment]
> 你要是能看见图，就重新传一份替换掉吧。

已替换。
