### ISSUE TITLE
建议增加 RSS feed

### ISSUE THREAD

**Issue by sbilly** [cosname/cosx.org#993]
建议增加 RSS feed，方便订阅。

**Comment by yufree** [comment]
感谢关注！主站的RSS的地址为 <http://cos.name/feed/>，稍后会在主站主题的 [底部](https://github.com/cosname/cosx.org/blob/4b3fcf2314beabd11912a0c43dea13c2d295e5de/config.toml#L72) 加入链接。

**Comment by yufree** [comment]
已更新 5169864
